/**
 * Canonical API route registry.
 *
 * One place where every path, its owner, its RBAC roles, its rate-limit policy
 * and its latency budget are declared together. This is what lets the architect
 * audit the whole HTTP surface in one file, and what lets `@smart/api-client`
 * stay in sync without guessing.
 *
 * Adding an endpoint means adding an entry here. An endpoint with no entry has
 * no declared limit and no declared roles, and fails review.
 *
 * Owner: Tino (System Architect).
 */

import type { UserRole } from '../domain/enums.js';

export const API_PREFIX = '/api/v1' as const;

/**
 * How tight the latency budget is, and why.
 *
 * ARCHITECTURE.md §3.2 sets < 200 ms for "the active test player and the
 * verification lookup" — not for every endpoint. A cohort analytics report that
 * takes 300 ms is fine; a 300 ms `next-item` call during a timed exam is not.
 * Making the distinction explicit stops the budget from being either violated
 * silently or applied so broadly that it becomes meaningless.
 */
export type RouteCriticality =
  /** In the candidate's timed exam path, or the employer verification path. Hard 200 ms ceiling. */
  | 'CANDIDATE_CRITICAL'
  /**
   * A live LLM turn (the L4 interactive defense). Latency is bounded by the
   * model, not by our code, so it gets its own budget and the P1 priority lane
   * that reserves 40 % of AI quota — a candidate mid-defense must never queue
   * behind a batch JD parse.
   */
  | 'LLM_INTERACTIVE'
  /** Interactive but not exam-timed: dashboards, auth handshakes, admin actions. */
  | 'INTERACTIVE'
  /** Aggregation and reporting. Slower is acceptable; correctness matters more. */
  | 'REPORTING';

export interface RouteSpec {
  readonly method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly module: string;
  readonly owner: string;
  readonly roles: readonly UserRole[];
  /** Key into ENDPOINT_RATE_LIMITS / ROLE_RATE_LIMITS. */
  readonly rateLimit: string;
  readonly execution: 'SYNC' | 'ASYNC';
  readonly criticality: RouteCriticality;
  /** Latency budget for SYNC routes (ARCHITECTURE.md §3.2). */
  readonly slaMs?: number;
  readonly summary: string;
}

/** Latency ceiling per criticality class. Asserted in CI by the contract invariants. */
export const LATENCY_BUDGET_MS: Readonly<Record<RouteCriticality, number>> = {
  CANDIDATE_CRITICAL: 200,
  LLM_INTERACTIVE: 6_000,
  INTERACTIVE: 500,
  REPORTING: 1_000,
} as const;

export const ROUTES: readonly RouteSpec[] = [
  /* ------------------------------ auth & users ---------------------------- */
  {
    method: 'POST',
    path: '/auth/login',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.login',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Password login; issues access token + refresh cookie.',
  },
  {
    method: 'POST',
    path: '/auth/sso/start',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.login',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Begin OAuth / SAML / OIDC flow.',
  },
  {
    method: 'POST',
    path: '/auth/sso/callback',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.login',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Complete SSO handshake.',
  },
  {
    method: 'POST',
    path: '/auth/refresh',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.refresh',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Rotate refresh token, issue new access token.',
  },
  {
    method: 'POST',
    path: '/auth/logout',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'SUPER_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Revoke the refresh token family.',
  },
  {
    method: 'GET',
    path: '/users/me',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'SUPER_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 50,
    summary: 'Current profile and track enrolments.',
  },
  {
    method: 'PUT',
    path: '/users/me/track',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Enroll on or change a specialisation track.',
  },
  {
    method: 'POST',
    path: '/users/me/password',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'SUPER_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Change password while authenticated; revokes all refresh families.',
  },
  {
    method: 'POST',
    path: '/users/me/resume/parse',
    module: 'ai-gateway',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'users.resumeParse',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6_000,
    summary:
      'Parse an uploaded resume into a pre-fill draft (education, experience, skills). Manual edit always allowed.',
  },
  {
    method: 'GET',
    path: '/users/me/onboarding',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Load persisted candidate onboarding profile (null until completed).',
  },
  {
    method: 'POST',
    path: '/users/me/onboarding/complete',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary:
      'Persist profile + DPDP consent and set onboardingCompleted=true (CN-T01 server gate).',
  },
  {
    method: 'PUT',
    path: '/users/me/onboarding',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 120,
    summary:
      'Save in-progress candidate onboarding data as a draft. Does not set onboardingCompleted.',
  },
  {
    method: 'GET',
    path: '/users/me/onboarding/linkedin/oauth-url',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Begin "Sign in with LinkedIn" (OIDC) identity verification.',
  },
  {
    method: 'GET',
    path: '/users/onboarding/linkedin/callback',
    module: 'users',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'role.public',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary:
      'LinkedIn OIDC redirect landing — exchanges the code and redirects back to onboarding.',
  },
  {
    method: 'POST',
    path: '/users/me/onboarding/github/fetch-profile',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 400,
    summary: 'Look up a public GitHub profile by URL for the identity confirm card.',
  },
  {
    method: 'POST',
    path: '/users/me/onboarding/github/list-repos',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 400,
    summary: "List a GitHub user's public, non-fork repos for the repo picker.",
  },
  {
    method: 'POST',
    path: '/users/me/onboarding/github/repo-languages',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 500,
    summary: "Aggregate language byte-share across the candidate's 3-5 chosen repos.",
  },
  {
    method: 'POST',
    path: '/users/me/github/repo-readme',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 500,
    summary: "Fetch a repo's README to prefill a project submission.",
  },
  {
    method: 'GET',
    path: '/users/me/work-experiences',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List candidate work experience entries with document metadata.',
  },
  {
    method: 'GET',
    path: '/users/me/work-experiences/:id',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Get single candidate work experience record by ID.',
  },
  {
    method: 'POST',
    path: '/users/me/work-experiences',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Create a candidate work experience entry.',
  },
  {
    method: 'PUT',
    path: '/users/me/work-experiences/:id',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Update candidate work experience entry.',
  },
  {
    method: 'DELETE',
    path: '/users/me/work-experiences/:id',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 120,
    summary: 'Delete candidate work experience entry.',
  },
  {
    method: 'POST',
    path: '/users/me/work-experiences/:id/documents',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Attach proof document metadata to a work experience record.',
  },
  {
    method: 'DELETE',
    path: '/users/me/work-experiences/:id/documents/:documentId',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 120,
    summary: 'Remove proof document attachment from a work experience record.',
  },
  {
    method: 'POST',
    path: '/users/me/work-experiences/:id/documents/:documentId/validate',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 5_000,
    summary: 'Validate an attached work experience proof document using AI classification.',
  },
  {
    method: 'POST',
    path: '/users/me/work-experiences/:id/send-verification',
    module: 'users',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Dispatch employer verification email with secure single-use token to verifier.',
  },
  {
    method: 'GET',
    path: '/users/work-experiences/verify-token/:token',
    module: 'users',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'verify.workExperience',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Public endpoint to view work experience details by verification token.',
  },
  {
    method: 'POST',
    path: '/users/work-experiences/verify-token/:token',
    module: 'users',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'verify.workExperience',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 200,
    summary:
      'Public endpoint for employer verifier to approve or reject candidate work experience claim.',
  },
  {
    method: 'POST',
    path: '/admin/api-keys',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Issue a B2B API key.',
  },
  {
    method: 'GET',
    path: '/auth/invitations/:token',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.invite',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Preview an invitation before password setup.',
  },
  {
    method: 'POST',
    path: '/auth/invitations/:token/accept',
    module: 'auth',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'auth.invite',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Accept invitation and set password; issues access token.',
  },
  {
    method: 'POST',
    path: '/admin/institutions',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Create an institution.',
  },
  {
    method: 'GET',
    path: '/admin/institutions',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List all institutions.',
  },
  {
    method: 'GET',
    path: '/admin/institutions/:institutionId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Get one institution.',
  },
  {
    method: 'POST',
    path: '/admin/institutions/:institutionId/admins',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Invite an institution admin; enqueues email.',
  },
  {
    method: 'GET',
    path: '/admin/institutions/:institutionId/admins',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List institution admins and invite status.',
  },
  {
    method: 'POST',
    path: '/admin/invitations/:invitationId/resend',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Resend a platform-admin invitation email.',
  },
  {
    method: 'PATCH',
    path: '/admin/institutions/:institutionId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Update institution name, domain, or plan.',
  },
  {
    method: 'POST',
    path: '/admin/institutions/:institutionId/hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Put an institution on hold; associated users cannot log in.',
  },
  {
    method: 'POST',
    path: '/admin/institutions/:institutionId/release-hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Release an institution from hold.',
  },
  {
    method: 'POST',
    path: '/admin/institutions/:institutionId/deactivate',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Soft-delete an institution; data is kept, logins are locked.',
  },
  {
    method: 'POST',
    path: '/admin/institutions/:institutionId/restore',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Restore a soft-deleted institution.',
  },
  {
    method: 'GET',
    path: '/admin/institutions/:institutionId/students',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'List students for an institution with invite-status filters.',
  },
  {
    method: 'GET',
    path: '/admin/students/search',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Global student search by name or email (lookup only).',
  },
  {
    method: 'GET',
    path: '/admin/plans',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List subscription plans and entitlement flags.',
  },
  {
    method: 'PATCH',
    path: '/admin/plans/:planId/entitlements',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Update boolean entitlements for a subscription plan.',
  },
  {
    method: 'PUT',
    path: '/admin/institutions/:institutionId/feature-flags',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Set a per-institution feature-flag override.',
  },
  {
    method: 'GET',
    path: '/admin/institutions/:institutionId/entitlements',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Resolved entitlements for an institution (plan plus overrides).',
  },
  {
    method: 'GET',
    path: '/tpo/entitlements',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Resolved entitlements for the caller institution.',
  },
  {
    method: 'GET',
    path: '/admin/dashboard',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 250,
    summary: 'Platform ops dashboard counts and recent audit.',
  },
  {
    method: 'GET',
    path: '/admin/audit-logs',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Searchable audit log of sensitive admin actions.',
  },
  {
    method: 'POST',
    path: '/admin/students/:userId/profile',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Reason-gated brief candidate profile; writes one audit row.',
  },
  {
    method: 'POST',
    path: '/admin/companies',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Create a company tenant.',
  },
  {
    method: 'GET',
    path: '/admin/companies',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List company tenants.',
  },
  {
    method: 'GET',
    path: '/admin/companies/:companyId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Get one company tenant.',
  },
  {
    method: 'PATCH',
    path: '/admin/companies/:companyId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Update company profile or plan.',
  },
  {
    method: 'POST',
    path: '/admin/companies/:companyId/hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Put a company on hold.',
  },
  {
    method: 'POST',
    path: '/admin/companies/:companyId/release-hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Release a company from hold.',
  },
  {
    method: 'POST',
    path: '/admin/companies/:companyId/deactivate',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Soft-deactivate a company.',
  },
  {
    method: 'POST',
    path: '/admin/companies/:companyId/restore',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Restore a deactivated company.',
  },
  {
    method: 'GET',
    path: '/admin/verification-queue',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Self-onboarding verification queue for institutions and companies.',
  },
  {
    method: 'POST',
    path: '/admin/verification-queue/:tenantId/resolve',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Approve or reject a self-onboarded tenant.',
  },
  {
    method: 'GET',
    path: '/tpo/students',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'List students in the TPO institution with invite and hold status.',
  },
  {
    method: 'POST',
    path: '/tpo/students/:userId/invite-link',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: "Mint (or re-mint) a student's invite link for the TPO to copy and share offline.",
  },
  {
    method: 'POST',
    path: '/tpo/students/:userId/hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Put one student account on hold.',
  },
  {
    method: 'POST',
    path: '/tpo/students/:userId/release-hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Release a student account from hold.',
  },
  {
    method: 'POST',
    path: '/admin/students/:userId/hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Put one student account on hold (platform admin).',
  },
  {
    method: 'POST',
    path: '/admin/students/:userId/release-hold',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Release a student account from hold (platform admin).',
  },
  {
    method: 'POST',
    path: '/tpo/batches',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Create a batch for the institution.',
  },
  {
    method: 'GET',
    path: '/tpo/batches',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'List batches for the institution.',
  },
  {
    method: 'GET',
    path: '/tpo/batches/:batchId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Get one batch.',
  },
  {
    method: 'PATCH',
    path: '/tpo/batches/:batchId',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Update batch name or code.',
  },
  {
    method: 'POST',
    path: '/tpo/batches/:batchId/members',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Add one student to a batch.',
  },
  {
    method: 'POST',
    path: '/tpo/batches/:batchId/members/import',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'tpo.import',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 500,
    summary: 'Preview or bulk import students from a mapped CSV or XLSX file.',
  },
  {
    method: 'GET',
    path: '/tpo/batches/:batchId/members',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'List batch members and invite status.',
  },
  {
    method: 'GET',
    path: '/tpo/batches/:batchId/import-template',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Download Excel import template.',
  },
  {
    method: 'POST',
    path: '/tpo/batches/:batchId/invites/send',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Enqueue invitation emails for all pending members.',
  },
  {
    method: 'POST',
    path: '/tpo/invitations/:invitationId/resend',
    module: 'institutions',
    owner: 'Vishal V',
    roles: ['INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Resend one student invitation email.',
  },

  /* -------------------------------- catalog -------------------------------- */
  {
    method: 'GET',
    path: '/catalog/tracks',
    module: 'catalog',
    owner: 'Vedika G',
    roles: ['PUBLIC'],
    rateLimit: 'role.public',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'All tracks with domains and levels.',
  },
  {
    method: 'GET',
    path: '/catalog/tracks/:trackCode',
    module: 'catalog',
    owner: 'Vedika G',
    roles: ['PUBLIC'],
    rateLimit: 'role.public',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'One track with competencies.',
  },
  {
    method: 'GET',
    path: '/catalog/readiness',
    module: 'catalog',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN', 'INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Item-bank and calibration readiness per track.',
  },

  /* ------------------------------- assessment ------------------------------ */
  {
    method: 'POST',
    path: '/assessment/next-form',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Select next item form (parallel-form rotation + exposure tracking)',
  },
  {
    method: 'POST',
    path: '/assessment/start',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Open an attempt; assigns a parallel form.',
  },
  {
    method: 'GET',
    path: '/assessment/:attemptId/session',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 50,
    summary: 'Resume state after refresh or reconnect.',
  },
  {
    method: 'GET',
    path: '/assessment/:attemptId/next-item',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 50,
    summary: 'Next item from the warm cache; zero DB hit.',
  },
  {
    method: 'POST',
    path: '/assessment/submit-l1',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'assessment.submitL1',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 30,
    summary: 'Save an answer draft (write-through to Redis).',
  },
  {
    method: 'POST',
    path: '/assessment/compile-l2',
    module: 'sandbox',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'assessment.compileL2',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'ASYNC',
    summary: 'Queue code/SQL execution; returns a jobId.',
  },
  {
    method: 'GET',
    path: '/assessment/sandbox/:jobId',
    module: 'sandbox',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 50,
    summary: 'Poll sandbox execution result.',
  },
  {
    method: 'POST',
    path: '/assessment/l3/upload-url',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Presigned R2 URL for direct audio upload.',
  },
  {
    method: 'POST',
    path: '/assessment/evaluate-l3-l4',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'assessment.evaluateL3L4',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'ASYNC',
    summary: 'Queue BARS or defense evaluation.',
  },
  {
    method: 'POST',
    path: '/assessment/complete',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'ASYNC',
    summary: 'Finalise attempt; emits smart.assessment.submitted.',
  },
  {
    method: 'POST',
    path: '/assessment/integrity-event',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 30,
    summary: 'Client integrity telemetry (advisory). HMAC ingest lives under /proctoring.',
  },

  /* ------------------------------ proctoring ------------------------------- */
  {
    method: 'GET',
    path: '/proctoring/:attemptId/nonce',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 50,
    summary: 'Single-use HMAC nonce for a violation event.',
  },
  {
    method: 'GET',
    path: '/proctoring/:attemptId/snapshot',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Warning count, lock, HMAC secret, integrity band.',
  },
  {
    method: 'GET',
    path: '/proctoring/:attemptId/blob',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Latest Blob HUD payload (Redis fan-out stand-in for WS).',
  },
  {
    method: 'POST',
    path: '/proctoring/violations',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'HMAC-SHA256 signed violation ingest.',
  },
  {
    method: 'POST',
    path: '/proctoring/ping',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 40,
    summary: 'Session heartbeat.',
  },
  {
    method: 'POST',
    path: '/proctoring/fingerprint',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.telemetry',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Device fingerprint baseline / mismatch.',
  },
  {
    method: 'POST',
    path: '/proctoring/checkpoint',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'ASYNC',
    summary: 'Enqueue webcam objectKey for CV sidecar.',
  },
  {
    method: 'POST',
    path: '/proctoring/consent',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'DPDP opt-in for camera, mic, and biometric processing.',
  },
  {
    method: 'GET',
    path: '/proctoring/:attemptId/onboarding',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Onboarding gate status.',
  },
  {
    method: 'POST',
    path: '/proctoring/precheck',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Lighting, centering, and ambient RMS pre-check.',
  },
  {
    method: 'POST',
    path: '/proctoring/enroll-face',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 400,
    summary: 'Face enrollment (sidecar stub in CI).',
  },
  {
    method: 'POST',
    path: '/proctoring/liveness',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Active liveness challenge result.',
  },
  {
    method: 'POST',
    path: '/proctoring/calibrate-voice',
    module: 'proctoring',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'proctoring.media',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 400,
    summary: 'Voice passphrase calibration.',
  },
  {
    method: 'GET',
    path: '/evaluation/results/:attemptId',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT', 'INSTITUTION_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Itemised score and tier breakdown.',
  },

  /* ------------------------------ L4 defense ------------------------------- */
  {
    method: 'POST',
    path: '/defense/start',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'assessment.evaluateL3L4',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 2000,
    summary: 'Open an interactive L4 defense session (P1 lane).',
  },
  {
    method: 'POST',
    path: '/defense/reply',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'assessment.evaluateL3L4',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 5000,
    summary: 'Submit a defense turn, receive the follow-up question.',
  },

  /* ------------------------ skill interview (SE-T02) ----------------------- */
  {
    method: 'POST',
    path: '/evaluation/skill-interview/questions',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 4000,
    summary: 'Generate three skill-relevant interview questions (cached per skill when possible).',
  },
  {
    method: 'POST',
    path: '/evaluation/skill-interview/grade',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 5000,
    summary: 'Score typed/transcribed answers; always returns pass/fail plus a one-line why.',
  },
  {
    method: 'POST',
    path: '/evaluation/skill-form/questions',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6000,
    summary: 'Generate an SDE v4 skill-verification form. Public items plus opaque scoringToken.',
  },
  {
    method: 'POST',
    path: '/evaluation/skill-form/grade',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6000,
    summary: 'Grade an SDE v4 form (closed local, open via one batch LLM call).',
  },

  /* -------------------- project verification (SE-T03) ---------------------- */
  {
    method: 'GET',
    path: '/projects/github/status',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Whether the student has a repo-read GitHub token (not login-only OAuth).',
  },
  {
    method: 'GET',
    path: '/projects/github/repos',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.github',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 400,
    summary: 'Top GitHub repos for the CN-T08 picker (cached; VV implements Octokit).',
  },
  {
    method: 'POST',
    path: '/projects',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'projects.submit',
    criticality: 'INTERACTIVE',
    execution: 'ASYNC',
    summary: 'Create a project from the CN-T08 template and enqueue snapshot + SE-T03.',
  },
  {
    method: 'GET',
    path: '/projects',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: "List the caller's own submitted projects, newest first.",
  },
  {
    method: 'GET',
    path: '/projects/:projectId',
    module: 'evaluation',
    owner: 'Ramansh',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Project row plus verification report; poll while status is SUBMITTED.',
  },
  {
    method: 'GET',
    path: '/admin/project-review-queue',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Projects routed to human review. Not the attempt integrity queue.',
  },
  {
    method: 'POST',
    path: '/admin/project-review-queue/:projectId/resolve',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Human APPROVE (VERIFIED) or REJECT. The agent never rejects.',
  },

  /* ------------------------------- calibration ----------------------------- */
  {
    method: 'POST',
    path: '/calibration/panels',
    module: 'calibration',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Create a calibration panel for a track+level.',
  },
  {
    method: 'POST',
    path: '/calibration/estimates',
    module: 'calibration',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Record panelist Angoff estimates.',
  },
  {
    method: 'POST',
    path: '/calibration/cut-scores/publish',
    module: 'calibration',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Derive mu±sigma and publish; emits smart.track.updated.',
  },
  {
    method: 'GET',
    path: '/calibration/cut-scores/:trackCode',
    module: 'calibration',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN', 'INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'Published cut scores per level.',
  },

  /* ------------------------------- certificate ----------------------------- */
  {
    method: 'POST',
    path: '/certificates/issue',
    module: 'certificate',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN', 'INSTITUTION_ADMIN'],
    rateLimit: 'certificate.issue',
    criticality: 'INTERACTIVE',
    execution: 'ASYNC',
    summary: 'Issue a certificate; blocked on an integrity hold.',
  },
  {
    method: 'GET',
    path: '/certificates/mine',
    module: 'certificate',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'The student\u2019s own certificates.',
  },
  {
    method: 'PATCH',
    path: '/certificates/:certificateId/visibility',
    module: 'certificate',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Student-controlled public visibility toggle.',
  },
  {
    method: 'GET',
    path: '/certificates/:certificateId/pdf',
    module: 'certificate',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT', 'INSTITUTION_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 120,
    summary: 'Signed direct R2 download URL.',
  },
  {
    method: 'GET',
    path: '/verify/:certificateId',
    module: 'certificate',
    owner: 'Vishal Bharath R',
    roles: ['PUBLIC'],
    rateLimit: 'verify.certificate',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 80,
    summary: 'PUBLIC verification payload. Redis cached, 1h TTL.',
  },

  /* -------------------------------- placement ------------------------------ */
  {
    method: 'POST',
    path: '/placement/ingest-jd',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'placement.ingestJd',
    criticality: 'INTERACTIVE',
    execution: 'ASYNC',
    summary: 'Upload and parse a JD into threshold vectors.',
  },
  {
    method: 'POST',
    path: '/placement/match',
    module: 'matching',
    owner: 'Ramansh',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'B2B_PARTNER'],
    rateLimit: 'placement.match',
    criticality: 'INTERACTIVE',
    execution: 'ASYNC',
    summary: 'Rank verified pool. V1 method is RULES (ADR 0012); cosine is optional HYBRID.',
  },
  {
    method: 'GET',
    path: '/tpo/shortlist',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.placementStaff',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Filterable shortlist for a recruiting drive.',
  },
  {
    method: 'GET',
    path: '/tpo/shortlist/export',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.placementStaff',
    criticality: 'REPORTING',
    execution: 'ASYNC',
    summary: 'CSV / PDF / XLSX export.',
  },
  {
    method: 'POST',
    path: '/placement/outcomes',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.placementStaff',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Record a real interview/offer outcome.',
  },
  {
    method: 'POST',
    path: '/placement/openings',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'B2B_PARTNER'],
    rateLimit: 'placement.opening',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Create a structured job opening from taxonomy skills (no free-text JD required).',
  },
  {
    method: 'GET',
    path: '/placement/openings/:openingId',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'B2B_PARTNER'],
    rateLimit: 'role.placementStaff',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Read one job opening.',
  },
  {
    method: 'GET',
    path: '/placement/openings',
    module: 'placement',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'B2B_PARTNER'],
    rateLimit: 'role.placementStaff',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'List structured job openings for the authenticated TPO institution.',
  },
  {
    method: 'GET',
    path: '/placement/openings/:openingId/applications',
    module: 'placement',
    owner: 'Vishal Bharath R',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.placementStaff',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'List candidate applications for a job opening owned by caller institution.',
  },
  {
    method: 'POST',
    path: '/placement/applications',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'placement.application',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Create an application / shortlist row for a student against an opening.',
  },
  {
    method: 'PATCH',
    path: '/placement/applications/:applicationId/stage',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'B2B_PARTNER'],
    rateLimit: 'placement.application',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Move ATS stage; emits smart.application.stage_changed.',
  },
  {
    method: 'GET',
    path: '/placement/applications/:applicationId/confidence',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'placement.application',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'TPO-readable SE-T02 passed + explanation for a shortlisted application.',
  },
  {
    method: 'POST',
    path: '/placement/applications/:applicationId/send-to-company',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'placement.application',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Send a reviewed application to INTERVIEW after a complete SE-T02 result.',
  },
  {
    method: 'GET',
    path: '/me/applications',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'placement.application',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Candidate My Applications. Poll is enough for V1.',
  },
  {
    method: 'GET',
    path: '/me/notifications',
    module: 'notifications',
    owner: 'Vishal V',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'SUPER_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'In-app notifications for the authenticated user.',
  },
  {
    method: 'PATCH',
    path: '/me/notifications/:notificationId/read',
    module: 'notifications',
    owner: 'Vishal V',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF', 'SUPER_ADMIN'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Mark a single notification as read.',
  },
  {
    method: 'GET',
    path: '/assessment/skill-claims',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'assessment.skillClaim',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'List skill claims the matcher reads (same SkillClaimStatus enum).',
  },
  {
    method: 'POST',
    path: '/assessment/skill-claims',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'assessment.skillClaim',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary:
      'Declare a skill claim at DECLARED (CN-T04). Re-declare after LOCKED cooldown expires.',
  },
  {
    method: 'POST',
    path: '/assessment/skill-claims/:claimId/verify/start',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6000,
    summary:
      'Prepare (cooldown/claim gate, Redis session, no LLM) or generate SDE v4 items after proctoring. Additive; not L1 startAttempt.',
  },
  {
    method: 'GET',
    path: '/assessment/skill-verify/:sessionId',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'assessment.skillClaim',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Resume an SDE v4 skill-verify session. Server clock; scoringToken stays server-side.',
  },
  {
    method: 'POST',
    path: '/assessment/skill-verify/:sessionId/save',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'assessment.skillClaim',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Save skill-verify answers to Redis (TTL on the session key).',
  },
  {
    method: 'POST',
    path: '/assessment/skill-verify/:sessionId/complete',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['STUDENT'],
    rateLimit: 'evaluation.skillInterview',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6000,
    summary: 'Grade via evaluation, settle SkillClaim with v4 pass (no interview bar), emit Kafka.',
  },

  {
    method: 'GET',
    path: '/analytics/cohort-readiness',
    module: 'analytics',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'SUPER_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 250,
    summary: 'Gold/Silver/Bronze distribution per track.',
  },
  {
    method: 'GET',
    path: '/analytics/gap-report',
    module: 'analytics',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'SUPER_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Ranked batch competency gaps.',
  },
  {
    method: 'GET',
    path: '/analytics/correlation',
    module: 'analytics',
    owner: 'Vedika G',
    roles: ['INSTITUTION_ADMIN', 'SUPER_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 300,
    summary: 'Tier vs interview/offer conversion.',
  },
  {
    method: 'GET',
    path: '/student/growth-report',
    module: 'analytics',
    owner: 'Vedika G',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Itemised gap feedback for the student.',
  },

  /* ------------------------------- platform ops ---------------------------- */
  {
    method: 'GET',
    path: '/admin/platform-health',
    module: 'analytics',
    owner: 'Vedika G',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 250,
    summary: 'Super admin system health surface.',
  },
  {
    method: 'GET',
    path: '/admin/ai-health',
    module: 'ai-gateway',
    owner: 'Ramansh',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Provider circuits, token buckets, spend, scoring pause state.',
  },
  {
    method: 'POST',
    path: '/ai-gateway/complete',
    module: 'ai-gateway',
    owner: 'Ramansh',
    roles: ['SUPER_ADMIN', 'INSTITUTION_ADMIN', 'PLACEMENT_STAFF'],
    rateLimit: 'role.superAdmin',
    criticality: 'LLM_INTERACTIVE',
    execution: 'SYNC',
    slaMs: 6_000,
    summary: 'Internal LLM completion via the AI gateway; never called by students.',
  },
  {
    method: 'GET',
    path: '/admin/integrity-queue',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'REPORTING',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Attempts awaiting integrity review.',
  },
  {
    method: 'POST',
    path: '/admin/integrity-queue/:attemptId/resolve',
    module: 'assessment',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Clear or void a flagged attempt.',
  },
  {
    method: 'PUT',
    path: '/admin/rate-limits/:policyKey',
    module: 'rate-limit',
    owner: 'Vishal V',
    roles: ['SUPER_ADMIN'],
    rateLimit: 'role.superAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 100,
    summary: 'Runtime rate-limit override.',
  },
  {
    method: 'POST',
    path: '/admin/webhooks',
    module: 'webhooks',
    owner: 'Vishal Bharath R',
    roles: ['SUPER_ADMIN', 'INSTITUTION_ADMIN'],
    rateLimit: 'role.institutionAdmin',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Register an outbound webhook endpoint.',
  },

  /* -------------------------- public candidate profile ---------------------- */
  {
    method: 'GET',
    path: '/users/me/public-profile-link',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: "Get (or mint, on first call) this student's public-profile share link.",
  },
  {
    method: 'GET',
    path: '/users/me/public-profile',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Preview your own public profile exactly as an employer would see it.',
  },
  {
    method: 'GET',
    path: '/public/candidates/:slug',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'verify.publicProfile',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 200,
    summary: "Look up a candidate's public profile by share slug. No auth required.",
  },

  /* ----------------------- candidate certificate verification ---------------------- */
  {
    method: 'POST',
    path: '/candidate-certificates',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Declare a new external certificate (title + issuer).',
  },
  {
    method: 'GET',
    path: '/candidate-certificates',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: "List the caller's own declared certificates.",
  },
  {
    method: 'GET',
    path: '/candidate-certificates/:id',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Get one owned certificate.',
  },
  {
    method: 'POST',
    path: '/candidate-certificates/:id/upload',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'ASYNC',
    summary: 'Upload the certificate file (PDF/JPG/PNG, max 10MB) to object storage.',
  },
  {
    method: 'POST',
    path: '/candidate-certificates/:id/skills',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: "Replace the certificate's claimed skills and self-assessed proficiency.",
  },
  {
    method: 'PATCH',
    path: '/candidate-certificates/:id',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Update learning description, tools, and practical-application fields.',
  },
  {
    method: 'POST',
    path: '/candidate-certificates/:id/endorsement',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 300,
    summary:
      "Request a named endorser's (work email only) review; moves the certificate to IN_VERIFICATION.",
  },
  {
    method: 'GET',
    path: '/candidate-certificates/:id/verification/events',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['STUDENT'],
    rateLimit: 'role.student',
    criticality: 'INTERACTIVE',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'List the audit-trail events for one certificate.',
  },
  {
    method: 'GET',
    path: '/certificate-endorsements/:token',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'verify.certificateEndorsement',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 150,
    summary: 'Public endpoint for an endorser to view the certificate + candidate claims by token.',
  },
  {
    method: 'POST',
    path: '/certificate-endorsements/:token',
    module: 'platform',
    owner: 'Vishal V',
    roles: ['PUBLIC'],
    rateLimit: 'verify.certificateEndorsement',
    criticality: 'CANDIDATE_CRITICAL',
    execution: 'SYNC',
    slaMs: 200,
    summary: 'Public endpoint for an endorser to approve or reject a certificate.',
  },
] as const;

export function findRoute(method: RouteSpec['method'], path: string): RouteSpec | undefined {
  return ROUTES.find((route) => route.method === method && route.path === path);
}

export function routesOwnedBy(owner: string): readonly RouteSpec[] {
  return ROUTES.filter((route) => route.owner === owner);
}

export function routesForModule(module: string): readonly RouteSpec[] {
  return ROUTES.filter((route) => route.module === module);
}

/**
 * Synchronous routes whose declared SLA exceeds the budget for their
 * criticality class. Asserted empty in CI — a route that cannot meet its budget
 * must either be optimised or reclassified deliberately, never left to drift.
 */
export function routesExceedingLatencyBudget(): readonly RouteSpec[] {
  return ROUTES.filter(
    (route) =>
      route.execution === 'SYNC' &&
      route.slaMs !== undefined &&
      route.slaMs > LATENCY_BUDGET_MS[route.criticality],
  );
}

/** Routes in the candidate's timed exam path or the employer verification path. */
export function candidateCriticalRoutes(): readonly RouteSpec[] {
  return ROUTES.filter((route) => route.criticality === 'CANDIDATE_CRITICAL');
}
