/**
 * Authoritative per-skill competency topics and assessment profiles.
 * Regenerate contracts index: pnpm --filter @smart/content-pipeline codegen:competencies
 */
import type { SkillCategoryId } from '@smart/contracts';

export type ProficiencyVerificationOverride = Partial<{
  readonly realWorldApplicationRequired: boolean;
  readonly substantialApplicationRequired: boolean;
  readonly interviewRequired: boolean;
}>;

export type SkillRegistryProfile = {
  readonly topics: readonly [string, string, string, string, string, string];
  readonly sdeFormCode: string;
  readonly taskFamily: 'CODING' | 'APPLIED';
  readonly focusOptions: readonly string[];
  readonly flavorNotes: readonly string[];
  readonly proficiencyVerificationOverrides?: Partial<
    Record<
      'BEGINNER' | 'INTERMEDIATE' | 'PROFICIENT' | 'ADVANCED' | 'PROFESSIONAL',
      ProficiencyVerificationOverride
    >
  >;
};

export type CategoryAssessmentDefault = {
  readonly sdeFormCode: string;
  readonly taskFamily: 'CODING' | 'APPLIED';
};

export const CATEGORY_ASSESSMENT_DEFAULTS: Readonly<
  Record<SkillCategoryId, CategoryAssessmentDefault>
> = {
  PROGRAMMING_LANGUAGES: { sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS', taskFamily: 'CODING' },
  SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN: {
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
  },
  CLOUD_PLATFORMS: { sdeFormCode: 'SDE_DEPLOYMENT_CICD', taskFamily: 'APPLIED' },
  DEVOPS_INFRASTRUCTURE: { sdeFormCode: 'SDE_DEPLOYMENT_CICD', taskFamily: 'APPLIED' },
  DATABASES_DATA_MANAGEMENT: { sdeFormCode: 'SDE_DATABASE_SQL', taskFamily: 'CODING' },
  DATA_ENGINEERING_BIG_DATA: { sdeFormCode: 'SDE_DATABASE_SQL', taskFamily: 'APPLIED' },
  AI_ML_DATA_SCIENCE: { sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS', taskFamily: 'APPLIED' },
  CYBERSECURITY: { sdeFormCode: 'SDE_TESTING', taskFamily: 'APPLIED' },
  TESTING_QA_RELIABILITY: { sdeFormCode: 'SDE_TESTING', taskFamily: 'APPLIED' },
  MOBILE_DEVELOPMENT: { sdeFormCode: 'SDE_WEB_FRAMEWORKS', taskFamily: 'CODING' },
  FRONTEND_WEB_DEVELOPMENT: { sdeFormCode: 'SDE_WEB_FRAMEWORKS', taskFamily: 'CODING' },
  NETWORKING_SYSTEMS_ADMINISTRATION: {
    sdeFormCode: 'SDE_COMPUTER_NETWORKS',
    taskFamily: 'APPLIED',
  },
  EMERGING_TECHNOLOGY: { sdeFormCode: 'SDE_SYSTEM_DESIGN', taskFamily: 'APPLIED' },
  DELIVERY_PROCESS_TOOLING: { sdeFormCode: 'SDE_GIT', taskFamily: 'APPLIED' },
};

/** Six industry-aligned competency capability names per catalog skill. */
export const SKILL_REGISTRY_PROFILES: Readonly<Record<string, SkillRegistryProfile>> = {
  PYTHON_APPLICATION_BACKEND_DEVELOPMENT: {
    topics: [
      'Python syntax, idioms & standard library',
      'OOP, typing & backend framework basics',
      'REST APIs, data validation & persistence',
      'Async I/O, concurrency & service integration',
      'Testing, profiling & production debugging',
      'Backend architecture, packaging & deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Python', 'Django', 'FastAPI'],
    flavorNotes: ['Python data structures', 'API design', 'ORM patterns'],
    proficiencyVerificationOverrides: {
      ADVANCED: { realWorldApplicationRequired: false, interviewRequired: true },
    },
  },
  JAVA_ENTERPRISE_APPLICATION_DEVELOPMENT: {
    topics: [
      'Java language fundamentals & JVM basics',
      'OOP, collections & Spring Boot essentials',
      'Enterprise APIs, JPA & transaction management',
      'Concurrency, JVM tuning & microservice patterns',
      'JUnit testing, debugging & observability',
      'Enterprise architecture & modular design',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Java', 'Spring Boot', 'JPA'],
    flavorNotes: ['Spring DI', 'REST controllers', 'Exception handling'],
  },
  JAVASCRIPT_TYPESCRIPT_FULL_STACK_DEVELOPMENT: {
    topics: [
      'JavaScript/TypeScript language fundamentals',
      'DOM, async patterns & Node.js runtime',
      'React/Node full-stack component design',
      'State management, APIs & auth flows',
      'Testing, bundling & performance tuning',
      'Full-stack architecture & deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['TypeScript', 'Node.js', 'React'],
    flavorNotes: ['Promises/async', 'Component lifecycle', 'API integration'],
  },
  GO_GOLANG_FOR_HIGH_PERFORMANCE_SERVICES: {
    topics: [
      'Go syntax, interfaces & error handling',
      'Goroutines, channels & concurrency primitives',
      'HTTP services, middleware & stdlib patterns',
      'Performance profiling & memory management',
      'Testing, benchmarking & deployment',
      'Distributed service design with Go',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Go', 'Goroutines', 'net/http'],
    flavorNotes: ['Channel patterns', 'Context cancellation', 'Table-driven tests'],
  },
  C_NET_ENTERPRISE_DEVELOPMENT: {
    topics: [
      'C# language & .NET runtime fundamentals',
      'OOP, LINQ & ASP.NET Core basics',
      'Entity Framework, APIs & dependency injection',
      'Async/await, caching & enterprise patterns',
      'xUnit testing, diagnostics & performance',
      '.NET enterprise architecture & cloud deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['C#', 'ASP.NET Core', 'Entity Framework'],
    flavorNotes: ['Middleware pipeline', 'DI lifetimes', 'LINQ queries'],
  },
  C_SYSTEMS_PERFORMANCE_ENGINEERING: {
    topics: [
      'C++ syntax, memory model & pointers',
      'STL, algorithms & template basics',
      'Systems programming & low-level I/O',
      'Performance optimization & cache awareness',
      'Debugging, sanitizers & tooling',
      'Systems architecture & resource trade-offs',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['C++', 'Memory management', 'Performance'],
    flavorNotes: ['RAII', 'Move semantics', 'Big-O analysis'],
  },
  RUST_FOR_SYSTEMS_RELIABILITY_ENGINEERING: {
    topics: [
      'Ownership, borrowing & lifetimes',
      'Traits, enums & error handling idioms',
      'Async Rust, concurrency & safe parallelism',
      'Unsafe code, FFI & systems integration',
      'Testing, Clippy & reliability practices',
      'Reliable systems design with Rust',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Rust', 'Ownership', 'Tokio'],
    flavorNotes: ['Borrow checker', 'Result/Option', 'Cargo workflows'],
  },
  KOTLIN_FOR_ANDROID_BACKEND_SERVICES: {
    topics: [
      'Kotlin syntax, null safety & coroutines',
      'Android UI fundamentals & Jetpack',
      'Backend services with Ktor/Spring',
      'Functional patterns & interop with Java',
      'Testing, Gradle & CI for Kotlin projects',
      'Mobile/backend architecture with Kotlin',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Kotlin', 'Coroutines', 'Android'],
    flavorNotes: ['Extension functions', 'Flow API', 'Sealed classes'],
  },
  SWIFT_FOR_IOS_MACOS_DEVELOPMENT: {
    topics: [
      'Swift language & value/reference semantics',
      'UIKit/SwiftUI fundamentals',
      'iOS app architecture & navigation patterns',
      'Concurrency, Combine & async/await',
      'XCTest, Instruments & App Store readiness',
      'iOS/macOS system design & performance',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Swift', 'SwiftUI', 'Combine'],
    flavorNotes: ['Optionals', 'Protocol-oriented design', 'ARC'],
  },
  SQL_QUERY_OPTIMIZATION: {
    topics: [
      'SQL fundamentals & relational algebra',
      'Joins, subqueries & window functions',
      'Query plans, indexes & optimization',
      'Transactions, isolation & locking',
      'Stored procedures, views & CTEs',
      'Schema design for analytical workloads',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['Joins', 'Window functions', 'Query tuning'],
    flavorNotes: ['EXPLAIN plans', 'Index selection', 'CTE patterns'],
    proficiencyVerificationOverrides: {
      ADVANCED: { realWorldApplicationRequired: false, interviewRequired: true },
    },
  },
  R_FOR_STATISTICAL_COMPUTING: {
    topics: [
      'R syntax, vectors & data frames',
      'Descriptive stats & probability basics',
      'Visualization with ggplot2 & reporting',
      'Statistical modeling & R packages',
      'Reproducible research & R Markdown',
      'Analysis pipeline design & validation',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['dplyr', 'ggplot2', 'tidyr'],
    flavorNotes: ['Tidyverse', 'Hypothesis testing', 'Data wrangling'],
  },
  SCALA_FOR_DISTRIBUTED_DATA_SYSTEMS: {
    topics: [
      'Scala syntax, immutability & FP basics',
      'Collections, implicits & type classes',
      'Spark/Akka distributed programming',
      'Advanced type system & pattern matching',
      'Testing with ScalaTest & sbt workflows',
      'Distributed data system architecture',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Scala', 'Spark', 'Akka'],
    flavorNotes: ['Case classes', 'Higher-order functions', 'RDD/DataFrame'],
  },

  RESTFUL_GRAPHQL_API_DESIGN: {
    topics: [
      'HTTP/REST fundamentals & resource modeling',
      'API versioning, pagination & HATEOAS',
      'GraphQL schema design & resolvers',
      'Auth, rate limiting & API security',
      'API testing, documentation & SDK design',
      'Public API platform architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['REST', 'GraphQL', 'OpenAPI'],
    flavorNotes: ['N+1 queries', 'Idempotency keys', 'Error contracts'],
  },

  ALGORITHMIC_COMPLEXITY_PERFORMANCE_OPTIMIZATION: {
    topics: [
      'Big-O analysis & algorithm fundamentals',
      'Arrays, hashing & two-pointer techniques',
      'Trees, graphs & traversal algorithms',
      'Dynamic programming & greedy methods',
      'Performance profiling & optimization',
      'Algorithm selection for production systems',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Arrays & hashing', 'Trees', 'Dynamic programming'],
    flavorNotes: ['Graph BFS/DFS', 'Sliding window', 'Space-time trade-offs'],
  },
  AMAZON_WEB_SERVICES_AWS_ARCHITECTURE: {
    topics: [
      'AWS core services & Well-Architected pillars',
      'Compute (EC2, Lambda) & networking (VPC)',
      'Storage (S3, EBS) & database services (RDS/DynamoDB)',
      'IAM, security groups & secrets management',
      'CloudWatch, cost optimization & automation',
      'Production AWS landing zone architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['EC2', 'Lambda', 'S3'],
    flavorNotes: ['VPC design', 'IAM least privilege', 'Multi-AZ'],
    proficiencyVerificationOverrides: {
      ADVANCED: {
        realWorldApplicationRequired: true,
        substantialApplicationRequired: false,
        interviewRequired: true,
      },
      PROFESSIONAL: {
        realWorldApplicationRequired: true,
        substantialApplicationRequired: true,
        interviewRequired: true,
      },
    },
  },
  MICROSOFT_AZURE_CLOUD_ENGINEERING: {
    topics: [
      'Azure fundamentals & resource organization',
      'App Service, Functions & container apps',
      'Azure SQL, Cosmos DB & storage accounts',
      'Entra ID, RBAC & Key Vault',
      'Monitor, ARM/Bicep & cost management',
      'Enterprise Azure architecture patterns',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['App Service', 'Azure Functions', 'AKS'],
    flavorNotes: ['Resource groups', 'Managed identities', 'VNet integration'],
  },
  GOOGLE_CLOUD_PLATFORM_GCP_ENGINEERING: {
    topics: [
      'GCP core services & project hierarchy',
      'GCE, Cloud Run & GKE workloads',
      'Cloud Storage, BigQuery & Spanner',
      'IAM, VPC & Cloud Armor security',
      'Cloud Monitoring, Terraform & FinOps',
      'GCP multi-region architecture design',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['GKE', 'Cloud Run', 'BigQuery'],
    flavorNotes: ['Workload Identity', 'VPC peering', 'Pub/Sub'],
  },

  CI_CD_PIPELINE_ENGINEERING: {
    topics: [
      'CI/CD fundamentals & pipeline design',
      'Build, test & artifact promotion stages',
      'Deployment strategies & environment gates',
      'Pipeline security & supply chain hardening',
      'Observability, rollback & release metrics',
      'Enterprise delivery pipeline architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Docker', 'CI pipelines', 'Rollback'],
    flavorNotes: ['Trunk-based flow', 'Quality gates', 'DORA metrics'],
  },
  CONTAINERIZATION_ORCHESTRATION: {
    topics: [
      'Containers, images & Dockerfile best practices',
      'Kubernetes workloads, services & ingress',
      'Helm charts, namespaces & RBAC',
      'Scheduling, autoscaling & resource limits',
      'Cluster observability & troubleshooting',
      'Production Kubernetes platform design',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Docker', 'Kubernetes', 'Helm'],
    flavorNotes: ['Pod lifecycle', 'Liveness/readiness probes', 'Network policies'],
  },

  OBSERVABILITY_MONITORING: {
    topics: [
      'Metrics, logs & traces fundamentals',
      'Instrumentation & OpenTelemetry practices',
      'Dashboards, alerting & SLO burn rates',
      'Distributed tracing & correlation IDs',
      'Log aggregation & anomaly detection',
      'Observability platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Prometheus', 'Grafana', 'OpenTelemetry'],
    flavorNotes: ['RED/USE methods', 'Alert fatigue', 'Cardinality control'],
  },
  GITOPS_CONTINUOUS_DELIVERY: {
    topics: [
      'GitOps principles & Git as source of truth',
      'Argo CD/Flux reconciliation loops',
      'Environment promotion via PR workflows',
      'Drift detection & automated rollback',
      'Secrets management in GitOps pipelines',
      'GitOps platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Argo CD', 'Flux', 'GitOps'],
    flavorNotes: ['Reconciliation', 'App-of-apps', 'Progressive delivery'],
  },
  RELATIONAL_DATABASE_DESIGN_ADMINISTRATION: {
    topics: [
      'Relational modeling & normalization',
      'DDL, constraints & referential integrity',
      'Indexing strategies & query tuning',
      'Backup, recovery & replication',
      'Security, roles & audit logging',
      'Enterprise RDBMS architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['PostgreSQL', 'MySQL', 'Normalization'],
    flavorNotes: ['ACID properties', 'Replication lag', 'Partitioning'],
  },
  NOSQL_DATABASE_ENGINEERING: {
    topics: [
      'NoSQL data models & CAP trade-offs',
      'Document, key-value & wide-column stores',
      'Schema design & access pattern modeling',
      'Consistency, replication & sharding',
      'Performance tuning & operational tooling',
      'Polyglot persistence architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['MongoDB', 'DynamoDB', 'Redis'],
    flavorNotes: ['Eventual consistency', 'Hot partitions', 'TTL design'],
  },
  DATA_MODELING_NORMALIZATION: {
    topics: [
      'Conceptual & logical data modeling',
      'Normalization forms & denormalization trade-offs',
      'Dimensional modeling & star/snowflake schemas',
      'Slowly changing dimensions & historization',
      'Data dictionary & lineage documentation',
      'Enterprise data model governance',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['ER modeling', 'Star schema', 'SCD types'],
    flavorNotes: ['3NF vs denormalized', 'Surrogate keys', 'Bridge tables'],
  },
  DATABASE_PERFORMANCE_TUNING_INDEXING: {
    topics: [
      'Query execution plans & statistics',
      'Index types, covering indexes & selectivity',
      'Locking, blocking & deadlock analysis',
      'Partitioning & archival strategies',
      'Connection pooling & workload isolation',
      'Database performance architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['Query plans', 'Indexing', 'Locking'],
    flavorNotes: ['Missing indexes', 'Parameter sniffing', 'Read replicas'],
  },

  ETL_ELT_PIPELINE_DEVELOPMENT: {
    topics: [
      'Batch pipeline design & orchestration',
      'Extract, transform & load patterns',
      'Data quality checks & schema evolution',
      'Incremental processing & idempotent jobs',
      'Pipeline monitoring & failure recovery',
      'Production data pipeline architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['Airflow', 'dbt', 'Spark'],
    flavorNotes: ['Backfill strategies', 'SLA monitoring', 'Data contracts'],
  },
  BIG_DATA_PROCESSING_FRAMEWORKS: {
    topics: [
      'Distributed compute fundamentals (MapReduce lineage)',
      'Spark RDDs, DataFrames & Spark SQL',
      'Partitioning, shuffles & job optimization',
      'Batch vs streaming on big data platforms',
      'Cluster sizing, fault tolerance & debugging',
      'Big data platform architecture',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'APPLIED',
    focusOptions: ['Spark', 'Hadoop', 'Flink'],
    flavorNotes: ['Shuffle optimization', 'Data skew', 'Checkpointing'],
  },

  MACHINE_LEARNING_MODEL_DEVELOPMENT_DEPLOYMENT: {
    topics: [
      'ML fundamentals & supervised learning workflow',
      'Feature engineering & dataset splitting',
      'Model training, validation & bias checks',
      'Model deployment & serving patterns',
      'Monitoring drift, retraining & A/B tests',
      'Production ML system architecture',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['scikit-learn', 'XGBoost', 'Model serving'],
    flavorNotes: ['Train/val/test split', 'Cross-validation', 'Feature stores'],
  },
  DEEP_LEARNING_NEURAL_NETWORK_ENGINEERING: {
    topics: [
      'Neural network fundamentals & backpropagation',
      'CNN/RNN/Transformer architecture basics',
      'Training loops, optimizers & regularization',
      'Transfer learning & fine-tuning workflows',
      'GPU utilization, mixed precision & debugging',
      'Deep learning production architecture',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['PyTorch', 'TensorFlow', 'Transformers'],
    flavorNotes: ['Gradient clipping', 'Batch norm', 'Learning rate schedules'],
  },
  NATURAL_LANGUAGE_PROCESSING_NLP: {
    topics: [
      'Text preprocessing & tokenization',
      'Embeddings, classical NLP & evaluation metrics',
      'Sequence models & transformer architectures',
      'Fine-tuning LLMs for NLP tasks',
      'RAG, prompt engineering & guardrails',
      'NLP application architecture in production',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['Transformers', 'RAG', 'Tokenization'],
    flavorNotes: ['BLEU/ROUGE', 'Attention mechanisms', 'Hallucination mitigation'],
  },
  LARGE_LANGUAGE_MODEL_LLM_APPLICATION_ENGINEERING: {
    topics: [
      'LLM capabilities, limits & safety basics',
      'Prompt design, chaining & tool use',
      'RAG pipelines, vector stores & retrieval',
      'Fine-tuning, adapters & evaluation harnesses',
      'Latency, cost & caching strategies',
      'LLM application architecture at scale',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['RAG', 'Prompt engineering', 'Tool calling'],
    flavorNotes: ['Context windows', 'Guardrails', 'Embedding models'],
  },
  MLOPS_MODEL_LIFECYCLE_MANAGEMENT: {
    topics: [
      'MLOps principles & experiment tracking',
      'Feature stores & reproducible pipelines',
      'CI/CD for models & automated validation',
      'Model registry, promotion & rollback',
      'Production monitoring & drift detection',
      'MLOps platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['MLflow', 'Kubeflow', 'Model registry'],
    flavorNotes: ['Experiment tracking', 'Model cards', 'Canary deployments'],
  },
  COMPUTER_VISION_ENGINEERING: {
    topics: [
      'Image representation, preprocessing & augmentation',
      'Classical CV: filters, features & edge detection',
      'CNN architectures, transfer learning & fine-tuning',
      'Object detection, segmentation & tracking',
      'Model evaluation metrics & deployment pipelines',
      'End-to-end computer vision system design',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['OpenCV', 'CNNs', 'Object detection'],
    flavorNotes: ['IoU/mAP metrics', 'Data augmentation', 'ONNX export'],
  },
  STATISTICAL_ANALYSIS_EXPERIMENTATION: {
    topics: [
      'Descriptive stats & probability distributions',
      'Hypothesis testing & confidence intervals',
      'Regression, ANOVA & experimental design',
      'A/B testing, power analysis & sample size',
      'Causal inference & confounding control',
      'Experimentation platform & analytics governance',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['A/B testing', 'Regression', 'Power analysis'],
    flavorNotes: ['p-values vs effect size', 'Multiple comparisons', 'Randomization'],
  },
  APPLICATION_SECURITY_APPSEC: {
    topics: [
      'OWASP Top 10 & secure SDLC basics',
      'Input validation, XSS & injection prevention',
      'Authentication, session & CSRF defenses',
      'Secure coding reviews & SAST/DAST tooling',
      'Secrets management & dependency scanning',
      'Application security architecture & threat modeling',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['OWASP', 'SAST', 'Threat modeling'],
    flavorNotes: ['SQL injection', 'SSRF', 'Security headers'],
  },
  CLOUD_SECURITY_ENGINEERING: {
    topics: [
      'Shared responsibility model & cloud threats',
      'IAM, least privilege & federation',
      'Network segmentation & WAF/cloud armor',
      'Encryption at rest/in transit & KMS',
      'CSPM, misconfiguration detection & auditing',
      'Cloud security reference architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['IAM', 'CSPM', 'Zero trust'],
    flavorNotes: ['Security groups', 'KMS rotation', 'CloudTrail'],
  },
  PENETRATION_TESTING_VULNERABILITY_ASSESSMENT: {
    topics: [
      'Reconnaissance & vulnerability scanning',
      'Web app pentest methodology (OWASP WSTG)',
      'Network exploitation & privilege escalation',
      'Reporting, CVSS scoring & remediation guidance',
      'Red team tactics & social engineering awareness',
      'Offensive security program architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Burp Suite', 'Nmap', 'Metasploit'],
    flavorNotes: ['Scope/rules of engagement', 'Chained exploits', 'PoC reporting'],
  },

  PERFORMANCE_LOAD_TESTING: {
    topics: [
      'Performance testing types & objectives',
      'Workload modeling & scenario design',
      'Load/stress/soak test execution',
      'Metrics analysis & bottleneck identification',
      'Capacity planning from test results',
      'Performance engineering program design',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['JMeter', 'k6', 'Gatling'],
    flavorNotes: ['Percentiles p95/p99', 'Think time', 'Saturation points'],
  },
  CONTINUOUS_TESTING_QUALITY_ENGINEERING: {
    topics: [
      'Shift-left testing & quality gates',
      'Test orchestration in CI/CD pipelines',
      'Quality metrics & defect escape analysis',
      'Test environment provisioning & service virtualization',
      'Quality engineering coaching & standards',
      'Continuous quality platform architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Quality gates', 'Shift-left', 'Test orchestration'],
    flavorNotes: ['Definition of done', 'Flake detection', 'Coverage vs risk'],
  },
  API_CONTRACT_TESTING: {
    topics: [
      'Contract testing principles & consumer-driven contracts',
      'OpenAPI/AsyncAPI schema validation',
      'Pact/provider verification workflows',
      'Breaking change detection & versioning',
      'Mock servers & contract CI integration',
      'API contract testing platform design',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Pact', 'OpenAPI', 'Contract tests'],
    flavorNotes: ['Provider verification', 'Schema diffing', 'Backward compatibility'],
  },
  NATIVE_ANDROID_DEVELOPMENT: {
    topics: [
      'Android fundamentals & activity/fragment lifecycle',
      'Jetpack Compose/UI layout patterns',
      'Navigation, ViewModel & state management',
      'Networking, Room & background work',
      'Testing, profiling & Play Store requirements',
      'Android app architecture (Clean/MVI)',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['Kotlin', 'Jetpack Compose', 'Room'],
    flavorNotes: ['Lifecycle observers', 'Coroutines on Android', 'Material Design'],
  },
  NATIVE_IOS_DEVELOPMENT: {
    topics: [
      'iOS app lifecycle & SwiftUI/UIKit',
      'Navigation, state & dependency injection',
      'Networking, Core Data & background tasks',
      'Accessibility, localization & HIG compliance',
      'XCTest, TestFlight & release management',
      'iOS application architecture patterns',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['SwiftUI', 'UIKit', 'Core Data'],
    flavorNotes: ['Delegate patterns', 'App extensions', 'Push notifications'],
  },
  MODERN_FRONTEND_FRAMEWORKS: {
    topics: [
      'HTML/CSS/JS fundamentals & accessibility basics',
      'React/Vue/Angular component models',
      'Routing, forms & client-side state',
      'API integration, auth & error boundaries',
      'Testing, bundling & Core Web Vitals',
      'Frontend application architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['React', 'Vue', 'Angular'],
    flavorNotes: ['Hooks', 'Virtual DOM', 'SSR vs CSR'],
  },
  FRONTEND_PERFORMANCE_ENGINEERING: {
    topics: [
      'Core Web Vitals & performance budgets',
      'Bundle analysis, code splitting & lazy loading',
      'Rendering optimization & memoization',
      'Network waterfall, caching & CDN usage',
      'Profiling with Lighthouse & browser devtools',
      'Frontend performance architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['LCP', 'CLS', 'Code splitting'],
    flavorNotes: ['Tree shaking', 'Prefetch/preload', 'Image optimization'],
  },
  STATE_MANAGEMENT_COMPONENT_ARCHITECTURE: {
    topics: [
      'Component composition & design systems',
      'Local vs global state patterns',
      'Redux/Zustand/Context state libraries',
      'Side effects, async data & caching layers',
      'Testing components & state transitions',
      'Scalable frontend component architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['Redux', 'Zustand', 'Design systems'],
    flavorNotes: ['Selector memoization', 'Atomic design', 'Prop drilling avoidance'],
  },
  NETWORK_ARCHITECTURE_PROTOCOLS: {
    topics: [
      'OSI/TCP-IP & common protocol behavior',
      'IP addressing, routing & switching',
      'DNS, DHCP & load balancing fundamentals',
      'Firewalls, VPNs & network security basics',
      'Troubleshooting connectivity & packet analysis',
      'Enterprise network architecture design',
    ],
    sdeFormCode: 'SDE_COMPUTER_NETWORKS',
    taskFamily: 'APPLIED',
    focusOptions: ['TCP/IP', 'DNS', 'Routing'],
    flavorNotes: ['Subnetting', 'NAT', 'Wireshark basics'],
  },
  LINUX_SYSTEMS_ADMINISTRATION: {
    topics: [
      'Linux filesystem, users & permissions',
      'Process management & systemd services',
      'Package management & configuration files',
      'Shell scripting & automation',
      'Monitoring, logs & performance tuning',
      'Linux server fleet architecture',
    ],
    sdeFormCode: 'SDE_OPERATING_SYSTEMS',
    taskFamily: 'APPLIED',
    focusOptions: ['systemd', 'bash', 'SSH hardening'],
    flavorNotes: ['chmod/chown', 'journalctl', 'Cron vs timers'],
  },
  BLOCKCHAIN_SMART_CONTRACT_DEVELOPMENT: {
    topics: [
      'Blockchain fundamentals & consensus models',
      'Smart contract languages (Solidity/Rust)',
      'Token standards, wallets & transactions',
      'Security vulnerabilities & audit practices',
      'dApp frontends & oracle integration',
      'Blockchain application architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Solidity', 'Ethereum', 'Smart contracts'],
    flavorNotes: ['Reentrancy', 'Gas optimization', 'Upgrade patterns'],
  },
  INTERNET_OF_THINGS_IOT_ENGINEERING: {
    topics: [
      'IoT architecture & device connectivity',
      'Embedded protocols (MQTT, CoAP, BLE)',
      'Edge processing & firmware OTA updates',
      'IoT security, provisioning & PKI',
      'Telemetry pipelines & digital twins',
      'Industrial IoT platform design',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['MQTT', 'Edge computing', 'Device management'],
    flavorNotes: ['Device shadows', 'Firmware signing', 'Time-series ingestion'],
  },
  AUGMENTED_VIRTUAL_REALITY_DEVELOPMENT: {
    topics: [
      'XR fundamentals & hardware tracking',
      '3D math, rendering & scene graph basics',
      'Unity/Unreal XR development workflows',
      'Interaction design & spatial UX',
      'Performance optimization for headsets',
      'Immersive application architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'APPLIED',
    focusOptions: ['Unity XR', 'OpenXR', 'Spatial UX'],
    flavorNotes: ['Frame pacing', 'Hand tracking', 'Locomotion comfort'],
  },

  VERSION_CONTROL_CODE_COLLABORATION: {
    topics: [
      'Git fundamentals & branching strategies',
      'Pull requests, code review & merge policies',
      'Rebase, cherry-pick & conflict resolution',
      'Hooks, signed commits & repo hygiene',
      'Monorepo vs polyrepo collaboration patterns',
      'Engineering collaboration platform design',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Git', 'Pull requests', 'Trunk-based development'],
    flavorNotes: ['Merge vs rebase', 'Conventional commits', 'CODEOWNERS'],
  },
};
