/**
 * Authoritative per-skill competency topics and assessment profiles.
 * Regenerate contracts index: pnpm --filter @smart/content-pipeline codegen:competencies
 */
import type { SkillCategoryId } from '@smart/contracts';

export type ProficiencyVerificationOverride = Partial<{
  readonly realWorldApplicationRequired: boolean;
  readonly substantialApplicationRequired: boolean;
  readonly interviewRequired: boolean;
}>;

export type SkillRegistryProfile = {
  readonly topics: readonly [string, string, string, string, string, string];
  readonly sdeFormCode: string;
  readonly taskFamily: 'CODING' | 'APPLIED';
  readonly focusOptions: readonly string[];
  readonly flavorNotes: readonly string[];
  readonly proficiencyVerificationOverrides?: Partial<
    Record<
      'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'PROFESSIONAL',
      ProficiencyVerificationOverride
    >
  >;
};

export type CategoryAssessmentDefault = {
  readonly sdeFormCode: string;
  readonly taskFamily: 'CODING' | 'APPLIED';
};

export const CATEGORY_ASSESSMENT_DEFAULTS: Readonly<
  Record<SkillCategoryId, CategoryAssessmentDefault>
> = {
  PROGRAMMING_LANGUAGES: { sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS', taskFamily: 'CODING' },
  SOFTWARE_ARCHITECTURE_SYSTEM_DESIGN: {
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
  },
  CLOUD_PLATFORMS: { sdeFormCode: 'SDE_DEPLOYMENT_CICD', taskFamily: 'APPLIED' },
  DEVOPS_INFRASTRUCTURE: { sdeFormCode: 'SDE_DEPLOYMENT_CICD', taskFamily: 'APPLIED' },
  DATABASES_DATA_MANAGEMENT: { sdeFormCode: 'SDE_DATABASE_SQL', taskFamily: 'CODING' },
  DATA_ENGINEERING_BIG_DATA: { sdeFormCode: 'SDE_DATABASE_SQL', taskFamily: 'APPLIED' },
  AI_ML_DATA_SCIENCE: { sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS', taskFamily: 'APPLIED' },
  CYBERSECURITY: { sdeFormCode: 'SDE_TESTING', taskFamily: 'APPLIED' },
  TESTING_QA_RELIABILITY: { sdeFormCode: 'SDE_TESTING', taskFamily: 'APPLIED' },
  MOBILE_DEVELOPMENT: { sdeFormCode: 'SDE_WEB_FRAMEWORKS', taskFamily: 'CODING' },
  FRONTEND_WEB_DEVELOPMENT: { sdeFormCode: 'SDE_WEB_FRAMEWORKS', taskFamily: 'CODING' },
  NETWORKING_SYSTEMS_ADMINISTRATION: {
    sdeFormCode: 'SDE_COMPUTER_NETWORKS',
    taskFamily: 'APPLIED',
  },
  EMERGING_TECHNOLOGY: { sdeFormCode: 'SDE_SYSTEM_DESIGN', taskFamily: 'APPLIED' },
  DELIVERY_PROCESS_TOOLING: { sdeFormCode: 'SDE_GIT', taskFamily: 'APPLIED' },
};

/** Six industry-aligned competency capability names per catalog skill. */
export const SKILL_REGISTRY_PROFILES: Readonly<Record<string, SkillRegistryProfile>> = {
  PYTHON_APPLICATION_BACKEND_DEVELOPMENT: {
    topics: [
      'Python syntax, idioms & standard library',
      'OOP, typing & backend framework basics',
      'REST APIs, data validation & persistence',
      'Async I/O, concurrency & service integration',
      'Testing, profiling & production debugging',
      'Backend architecture, packaging & deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Python', 'Django', 'FastAPI'],
    flavorNotes: ['Python data structures', 'API design', 'ORM patterns'],
    proficiencyVerificationOverrides: {
      ADVANCED: { realWorldApplicationRequired: false, interviewRequired: true },
    },
  },
  JAVA_ENTERPRISE_APPLICATION_DEVELOPMENT: {
    topics: [
      'Java language fundamentals & JVM basics',
      'OOP, collections & Spring Boot essentials',
      'Enterprise APIs, JPA & transaction management',
      'Concurrency, JVM tuning & microservice patterns',
      'JUnit testing, debugging & observability',
      'Enterprise architecture & modular design',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Java', 'Spring Boot', 'JPA'],
    flavorNotes: ['Spring DI', 'REST controllers', 'Exception handling'],
  },
  JAVASCRIPT_TYPESCRIPT_FULL_STACK_DEVELOPMENT: {
    topics: [
      'JavaScript/TypeScript language fundamentals',
      'DOM, async patterns & Node.js runtime',
      'React/Node full-stack component design',
      'State management, APIs & auth flows',
      'Testing, bundling & performance tuning',
      'Full-stack architecture & deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['TypeScript', 'Node.js', 'React'],
    flavorNotes: ['Promises/async', 'Component lifecycle', 'API integration'],
  },
  GO_GOLANG_FOR_HIGH_PERFORMANCE_SERVICES: {
    topics: [
      'Go syntax, interfaces & error handling',
      'Goroutines, channels & concurrency primitives',
      'HTTP services, middleware & stdlib patterns',
      'Performance profiling & memory management',
      'Testing, benchmarking & deployment',
      'Distributed service design with Go',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Go', 'Goroutines', 'net/http'],
    flavorNotes: ['Channel patterns', 'Context cancellation', 'Table-driven tests'],
  },
  C_NET_ENTERPRISE_DEVELOPMENT: {
    topics: [
      'C# language & .NET runtime fundamentals',
      'OOP, LINQ & ASP.NET Core basics',
      'Entity Framework, APIs & dependency injection',
      'Async/await, caching & enterprise patterns',
      'xUnit testing, diagnostics & performance',
      '.NET enterprise architecture & cloud deployment',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['C#', 'ASP.NET Core', 'Entity Framework'],
    flavorNotes: ['Middleware pipeline', 'DI lifetimes', 'LINQ queries'],
  },
  C_SYSTEMS_PERFORMANCE_ENGINEERING: {
    topics: [
      'C++ syntax, memory model & pointers',
      'STL, algorithms & template basics',
      'Systems programming & low-level I/O',
      'Performance optimization & cache awareness',
      'Debugging, sanitizers & tooling',
      'Systems architecture & resource trade-offs',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['C++', 'Memory management', 'Performance'],
    flavorNotes: ['RAII', 'Move semantics', 'Big-O analysis'],
  },
  RUST_FOR_SYSTEMS_RELIABILITY_ENGINEERING: {
    topics: [
      'Ownership, borrowing & lifetimes',
      'Traits, enums & error handling idioms',
      'Async Rust, concurrency & safe parallelism',
      'Unsafe code, FFI & systems integration',
      'Testing, Clippy & reliability practices',
      'Reliable systems design with Rust',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Rust', 'Ownership', 'Tokio'],
    flavorNotes: ['Borrow checker', 'Result/Option', 'Cargo workflows'],
  },
  KOTLIN_FOR_ANDROID_BACKEND_SERVICES: {
    topics: [
      'Kotlin syntax, null safety & coroutines',
      'Android UI fundamentals & Jetpack',
      'Backend services with Ktor/Spring',
      'Functional patterns & interop with Java',
      'Testing, Gradle & CI for Kotlin projects',
      'Mobile/backend architecture with Kotlin',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Kotlin', 'Coroutines', 'Android'],
    flavorNotes: ['Extension functions', 'Flow API', 'Sealed classes'],
  },
  SWIFT_FOR_IOS_MACOS_DEVELOPMENT: {
    topics: [
      'Swift language & value/reference semantics',
      'UIKit/SwiftUI fundamentals',
      'iOS app architecture & navigation patterns',
      'Concurrency, Combine & async/await',
      'XCTest, Instruments & App Store readiness',
      'iOS/macOS system design & performance',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['Swift', 'SwiftUI', 'Combine'],
    flavorNotes: ['Optionals', 'Protocol-oriented design', 'ARC'],
  },
  SQL_QUERY_OPTIMIZATION: {
    topics: [
      'SQL fundamentals & relational algebra',
      'Joins, subqueries & window functions',
      'Query plans, indexes & optimization',
      'Transactions, isolation & locking',
      'Stored procedures, views & CTEs',
      'Schema design for analytical workloads',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['Joins', 'Window functions', 'Query tuning'],
    flavorNotes: ['EXPLAIN plans', 'Index selection', 'CTE patterns'],
    proficiencyVerificationOverrides: {
      ADVANCED: { realWorldApplicationRequired: false, interviewRequired: true },
    },
  },
  R_FOR_STATISTICAL_COMPUTING: {
    topics: [
      'R syntax, vectors & data frames',
      'Descriptive stats & probability basics',
      'Visualization with ggplot2 & reporting',
      'Statistical modeling & R packages',
      'Reproducible research & R Markdown',
      'Analysis pipeline design & validation',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'CODING',
    focusOptions: ['dplyr', 'ggplot2', 'tidyr'],
    flavorNotes: ['Tidyverse', 'Hypothesis testing', 'Data wrangling'],
  },
  SCALA_FOR_DISTRIBUTED_DATA_SYSTEMS: {
    topics: [
      'Scala syntax, immutability & FP basics',
      'Collections, implicits & type classes',
      'Spark/Akka distributed programming',
      'Advanced type system & pattern matching',
      'Testing with ScalaTest & sbt workflows',
      'Distributed data system architecture',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Scala', 'Spark', 'Akka'],
    flavorNotes: ['Case classes', 'Higher-order functions', 'RDD/DataFrame'],
  },
  DISTRIBUTED_SYSTEMS_DESIGN: {
    topics: [
      'Distributed systems fundamentals & CAP',
      'Consistency models & replication',
      'Partitioning, sharding & load balancing',
      'Fault tolerance & failure detection',
      'Distributed transactions & consensus',
      'Large-scale system architecture trade-offs',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['APIs', 'Caching', 'Scalability'],
    flavorNotes: ['Leader election', 'Eventual consistency', 'Backpressure'],
  },
  MICROSERVICES_ARCHITECTURE_SERVICE_DECOMPOSITION: {
    topics: [
      'Microservices principles & bounded contexts',
      'Service decomposition & domain boundaries',
      'Inter-service communication patterns',
      'Data ownership & sagas/choreography',
      'Observability & resilience in microservices',
      'Microservices platform architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['DDD', 'Service mesh', 'API gateways'],
    flavorNotes: ['Circuit breakers', 'Strangler fig', 'BFF pattern'],
  },
  EVENT_DRIVEN_ARCHITECTURE: {
    topics: [
      'Event-driven fundamentals & messaging basics',
      'Event schemas, versioning & contracts',
      'Pub/sub, queues & stream processing',
      'Event sourcing & CQRS patterns',
      'Reliability, ordering & idempotency',
      'Event platform architecture at scale',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Kafka', 'Event sourcing', 'CQRS'],
    flavorNotes: ['Outbox pattern', 'Dead letter queues', 'Schema registry'],
  },
  RESTFUL_GRAPHQL_API_DESIGN: {
    topics: [
      'HTTP/REST fundamentals & resource modeling',
      'API versioning, pagination & HATEOAS',
      'GraphQL schema design & resolvers',
      'Auth, rate limiting & API security',
      'API testing, documentation & SDK design',
      'Public API platform architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['REST', 'GraphQL', 'OpenAPI'],
    flavorNotes: ['N+1 queries', 'Idempotency keys', 'Error contracts'],
  },
  SCALABLE_SYSTEM_HIGH_AVAILABILITY_ARCHITECTURE: {
    topics: [
      'Scalability patterns & capacity planning',
      'Load balancing & auto-scaling',
      'High availability & disaster recovery',
      'Caching layers & CDN strategies',
      'Chaos engineering & failure injection',
      'HA architecture for mission-critical systems',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['HA', 'DR', 'Multi-region'],
    flavorNotes: ['RTO/RPO', 'Active-active', 'Graceful degradation'],
  },
  DOMAIN_DRIVEN_DESIGN_DDD: {
    topics: [
      'DDD strategic design & ubiquitous language',
      'Bounded contexts & context mapping',
      'Aggregates, entities & value objects',
      'Domain events & application services',
      'Tactical patterns in codebases',
      'DDD-driven system modernization',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Aggregates', 'Bounded contexts', 'Ubiquitous language'],
    flavorNotes: ['Anti-corruption layer', 'Repository pattern', 'Event storming'],
  },
  DESIGN_PATTERNS_CLEAN_ARCHITECTURE: {
    topics: [
      'GoF patterns & when to apply them',
      'SOLID principles in practice',
      'Clean/hexagonal architecture layers',
      'Dependency inversion & testability',
      'Refactoring to patterns under constraints',
      'Architecture governance & code quality',
    ],
    sdeFormCode: 'SDE_OOP',
    taskFamily: 'CODING',
    focusOptions: ['SOLID', 'Clean Architecture', 'Design patterns'],
    flavorNotes: ['Factory vs Strategy', 'Adapter pattern', 'Ports and adapters'],
  },
  ALGORITHMIC_COMPLEXITY_PERFORMANCE_OPTIMIZATION: {
    topics: [
      'Big-O analysis & algorithm fundamentals',
      'Arrays, hashing & two-pointer techniques',
      'Trees, graphs & traversal algorithms',
      'Dynamic programming & greedy methods',
      'Performance profiling & optimization',
      'Algorithm selection for production systems',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'CODING',
    focusOptions: ['Arrays & hashing', 'Trees', 'Dynamic programming'],
    flavorNotes: ['Graph BFS/DFS', 'Sliding window', 'Space-time trade-offs'],
  },
  API_GATEWAY_SERVICE_MESH_MANAGEMENT: {
    topics: [
      'API gateway routing & policy enforcement',
      'Authentication, mTLS & zero-trust basics',
      'Service mesh sidecars & traffic management',
      'Canary, blue-green & traffic splitting',
      'Mesh observability & security policies',
      'Platform networking architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Istio', 'Envoy', 'Kong'],
    flavorNotes: ['mTLS', 'Retry budgets', 'Rate limiting at edge'],
  },
  AMAZON_WEB_SERVICES_AWS_ARCHITECTURE: {
    topics: [
      'AWS core services & Well-Architected pillars',
      'Compute (EC2, Lambda) & networking (VPC)',
      'Storage (S3, EBS) & database services (RDS/DynamoDB)',
      'IAM, security groups & secrets management',
      'CloudWatch, cost optimization & automation',
      'Production AWS landing zone architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['EC2', 'Lambda', 'S3'],
    flavorNotes: ['VPC design', 'IAM least privilege', 'Multi-AZ'],
    proficiencyVerificationOverrides: {
      ADVANCED: {
        realWorldApplicationRequired: true,
        substantialApplicationRequired: false,
        interviewRequired: true,
      },
      PROFESSIONAL: {
        realWorldApplicationRequired: true,
        substantialApplicationRequired: true,
        interviewRequired: true,
      },
    },
  },
  MICROSOFT_AZURE_CLOUD_ENGINEERING: {
    topics: [
      'Azure fundamentals & resource organization',
      'App Service, Functions & container apps',
      'Azure SQL, Cosmos DB & storage accounts',
      'Entra ID, RBAC & Key Vault',
      'Monitor, ARM/Bicep & cost management',
      'Enterprise Azure architecture patterns',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['App Service', 'Azure Functions', 'AKS'],
    flavorNotes: ['Resource groups', 'Managed identities', 'VNet integration'],
  },
  GOOGLE_CLOUD_PLATFORM_GCP_ENGINEERING: {
    topics: [
      'GCP core services & project hierarchy',
      'GCE, Cloud Run & GKE workloads',
      'Cloud Storage, BigQuery & Spanner',
      'IAM, VPC & Cloud Armor security',
      'Cloud Monitoring, Terraform & FinOps',
      'GCP multi-region architecture design',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['GKE', 'Cloud Run', 'BigQuery'],
    flavorNotes: ['Workload Identity', 'VPC peering', 'Pub/Sub'],
  },
  MULTI_CLOUD_HYBRID_CLOUD_STRATEGY: {
    topics: [
      'Multi-cloud drivers & vendor neutrality',
      'Hybrid connectivity & identity federation',
      'Portable workloads & abstraction layers',
      'Cross-cloud networking & data sync',
      'Governance, compliance & cost across clouds',
      'Multi-cloud reference architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Hybrid cloud', 'Portability', 'Governance'],
    flavorNotes: ['Cloud exit strategy', 'Shared services', 'Policy as code'],
  },
  SERVERLESS_ARCHITECTURE: {
    topics: [
      'Serverless compute models & FaaS basics',
      'Event triggers, cold starts & concurrency',
      'API Gateway + Lambda/BFF patterns',
      'State management & durable workflows',
      'Observability, security & cost controls',
      'Serverless platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Lambda', 'Step Functions', 'EventBridge'],
    flavorNotes: ['Idempotent handlers', 'Provisioned concurrency', 'DLQ handling'],
  },
  CLOUD_COST_OPTIMIZATION_FINOPS: {
    topics: [
      'FinOps principles & cloud cost visibility',
      'Reserved instances, savings plans & rightsizing',
      'Tagging, chargeback & budget alerts',
      'Workload optimization & autoscaling policies',
      'Unit economics & cost anomaly detection',
      'FinOps operating model & governance',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Cost allocation', 'Rightsizing', 'Reserved capacity'],
    flavorNotes: ['Showback/chargeback', 'Spot instances', 'Idle resource cleanup'],
  },
  INFRASTRUCTURE_AS_CODE_IAC: {
    topics: [
      'IaC principles & declarative vs imperative',
      'Terraform/HCL modules & state management',
      'CloudFormation/Bicep & ARM templates',
      'Drift detection, testing & policy as code',
      'Secrets, environments & pipeline integration',
      'IaC platform architecture & standards',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Terraform', 'CloudFormation', 'Pulumi'],
    flavorNotes: ['Remote state', 'Module composition', 'Plan/apply gates'],
  },
  CI_CD_PIPELINE_ENGINEERING: {
    topics: [
      'CI/CD fundamentals & pipeline design',
      'Build, test & artifact promotion stages',
      'Deployment strategies & environment gates',
      'Pipeline security & supply chain hardening',
      'Observability, rollback & release metrics',
      'Enterprise delivery pipeline architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Docker', 'CI pipelines', 'Rollback'],
    flavorNotes: ['Trunk-based flow', 'Quality gates', 'DORA metrics'],
  },
  CONTAINERIZATION_ORCHESTRATION: {
    topics: [
      'Containers, images & Dockerfile best practices',
      'Kubernetes workloads, services & ingress',
      'Helm charts, namespaces & RBAC',
      'Scheduling, autoscaling & resource limits',
      'Cluster observability & troubleshooting',
      'Production Kubernetes platform design',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Docker', 'Kubernetes', 'Helm'],
    flavorNotes: ['Pod lifecycle', 'Liveness/readiness probes', 'Network policies'],
  },
  SITE_RELIABILITY_ENGINEERING_SRE: {
    topics: [
      'SRE principles, SLI/SLO/SLA & error budgets',
      'Incident response & blameless postmortems',
      'Toil reduction & automation',
      'Capacity planning & reliability testing',
      'On-call practices & runbook design',
      'SRE operating model at scale',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['SLOs', 'Incident response', 'Error budgets'],
    flavorNotes: ['MTTR/MTBF', 'Game days', 'Runbooks'],
  },
  OBSERVABILITY_MONITORING: {
    topics: [
      'Metrics, logs & traces fundamentals',
      'Instrumentation & OpenTelemetry practices',
      'Dashboards, alerting & SLO burn rates',
      'Distributed tracing & correlation IDs',
      'Log aggregation & anomaly detection',
      'Observability platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Prometheus', 'Grafana', 'OpenTelemetry'],
    flavorNotes: ['RED/USE methods', 'Alert fatigue', 'Cardinality control'],
  },
  CONFIGURATION_MANAGEMENT_AUTOMATION: {
    topics: [
      'Configuration management principles',
      'Ansible/Chef/Puppet automation patterns',
      'Desired-state enforcement & idempotency',
      'Secrets rotation & config drift remediation',
      'Inventory, roles & environment promotion',
      'Configuration platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Ansible', 'Chef', 'Puppet'],
    flavorNotes: ['Playbooks', 'Idempotent tasks', 'Inventory groups'],
  },
  GITOPS_CONTINUOUS_DELIVERY: {
    topics: [
      'GitOps principles & Git as source of truth',
      'Argo CD/Flux reconciliation loops',
      'Environment promotion via PR workflows',
      'Drift detection & automated rollback',
      'Secrets management in GitOps pipelines',
      'GitOps platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['Argo CD', 'Flux', 'GitOps'],
    flavorNotes: ['Reconciliation', 'App-of-apps', 'Progressive delivery'],
  },
  RELATIONAL_DATABASE_DESIGN_ADMINISTRATION: {
    topics: [
      'Relational modeling & normalization',
      'DDL, constraints & referential integrity',
      'Indexing strategies & query tuning',
      'Backup, recovery & replication',
      'Security, roles & audit logging',
      'Enterprise RDBMS architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['PostgreSQL', 'MySQL', 'Normalization'],
    flavorNotes: ['ACID properties', 'Replication lag', 'Partitioning'],
  },
  NOSQL_DATABASE_ENGINEERING: {
    topics: [
      'NoSQL data models & CAP trade-offs',
      'Document, key-value & wide-column stores',
      'Schema design & access pattern modeling',
      'Consistency, replication & sharding',
      'Performance tuning & operational tooling',
      'Polyglot persistence architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['MongoDB', 'DynamoDB', 'Redis'],
    flavorNotes: ['Eventual consistency', 'Hot partitions', 'TTL design'],
  },
  DATA_MODELING_NORMALIZATION: {
    topics: [
      'Conceptual & logical data modeling',
      'Normalization forms & denormalization trade-offs',
      'Dimensional modeling & star/snowflake schemas',
      'Slowly changing dimensions & historization',
      'Data dictionary & lineage documentation',
      'Enterprise data model governance',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['ER modeling', 'Star schema', 'SCD types'],
    flavorNotes: ['3NF vs denormalized', 'Surrogate keys', 'Bridge tables'],
  },
  DATABASE_PERFORMANCE_TUNING_INDEXING: {
    topics: [
      'Query execution plans & statistics',
      'Index types, covering indexes & selectivity',
      'Locking, blocking & deadlock analysis',
      'Partitioning & archival strategies',
      'Connection pooling & workload isolation',
      'Database performance architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'CODING',
    focusOptions: ['Query plans', 'Indexing', 'Locking'],
    flavorNotes: ['Missing indexes', 'Parameter sniffing', 'Read replicas'],
  },
  DATA_WAREHOUSING: {
    topics: [
      'Warehouse fundamentals & Kimball/Inmon approaches',
      'ETL/ELT into warehouse layers',
      'Fact/dimension design & aggregations',
      'Incremental loads & late-arriving data',
      'Query performance & materialized views',
      'Modern warehouse architecture (cloud DW)',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['Snowflake', 'Redshift', 'BigQuery'],
    flavorNotes: ['Staging layers', 'Conformed dimensions', 'Clustering keys'],
  },
  ETL_ELT_PIPELINE_DEVELOPMENT: {
    topics: [
      'Batch pipeline design & orchestration',
      'Extract, transform & load patterns',
      'Data quality checks & schema evolution',
      'Incremental processing & idempotent jobs',
      'Pipeline monitoring & failure recovery',
      'Production data pipeline architecture',
    ],
    sdeFormCode: 'SDE_DATABASE_SQL',
    taskFamily: 'APPLIED',
    focusOptions: ['Airflow', 'dbt', 'Spark'],
    flavorNotes: ['Backfill strategies', 'SLA monitoring', 'Data contracts'],
  },
  BIG_DATA_PROCESSING_FRAMEWORKS: {
    topics: [
      'Distributed compute fundamentals (MapReduce lineage)',
      'Spark RDDs, DataFrames & Spark SQL',
      'Partitioning, shuffles & job optimization',
      'Batch vs streaming on big data platforms',
      'Cluster sizing, fault tolerance & debugging',
      'Big data platform architecture',
    ],
    sdeFormCode: 'SDE_DSA',
    taskFamily: 'APPLIED',
    focusOptions: ['Spark', 'Hadoop', 'Flink'],
    flavorNotes: ['Shuffle optimization', 'Data skew', 'Checkpointing'],
  },
  STREAM_PROCESSING_MESSAGING_SYSTEMS: {
    topics: [
      'Stream processing concepts & event time',
      'Kafka/Pulsar messaging fundamentals',
      'Windowing, watermarks & stateful operators',
      'Exactly-once semantics & delivery guarantees',
      'Stream monitoring & replay strategies',
      'Real-time data platform architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Kafka', 'Flink', 'Kafka Streams'],
    flavorNotes: ['Consumer groups', 'Compaction', 'Late events'],
  },
  DATA_LAKE_LAKEHOUSE_ARCHITECTURE: {
    topics: [
      'Data lake vs warehouse vs lakehouse concepts',
      'Object storage layouts & open table formats',
      'Medallion/bronze-silver-gold layering',
      'Catalog, governance & access control',
      'Query engines & performance on lakehouse',
      'Modern lakehouse reference architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Delta Lake', 'Iceberg', 'Hudi'],
    flavorNotes: ['ACID on object storage', 'Time travel', 'Z-ordering'],
  },
  DATA_GOVERNANCE_QUALITY_ENGINEERING: {
    topics: [
      'Data governance frameworks & stewardship',
      'Data quality dimensions & profiling',
      'Lineage, catalog & metadata management',
      'Privacy, PII masking & compliance (GDPR)',
      'Quality SLAs, alerting & remediation',
      'Enterprise data governance operating model',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Data catalog', 'Lineage', 'Quality SLAs'],
    flavorNotes: ['Data contracts', 'PII classification', 'Stewardship roles'],
  },
  MACHINE_LEARNING_MODEL_DEVELOPMENT_DEPLOYMENT: {
    topics: [
      'ML fundamentals & supervised learning workflow',
      'Feature engineering & dataset splitting',
      'Model training, validation & bias checks',
      'Model deployment & serving patterns',
      'Monitoring drift, retraining & A/B tests',
      'Production ML system architecture',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['scikit-learn', 'XGBoost', 'Model serving'],
    flavorNotes: ['Train/val/test split', 'Cross-validation', 'Feature stores'],
  },
  DEEP_LEARNING_NEURAL_NETWORK_ENGINEERING: {
    topics: [
      'Neural network fundamentals & backpropagation',
      'CNN/RNN/Transformer architecture basics',
      'Training loops, optimizers & regularization',
      'Transfer learning & fine-tuning workflows',
      'GPU utilization, mixed precision & debugging',
      'Deep learning production architecture',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['PyTorch', 'TensorFlow', 'Transformers'],
    flavorNotes: ['Gradient clipping', 'Batch norm', 'Learning rate schedules'],
  },
  NATURAL_LANGUAGE_PROCESSING_NLP: {
    topics: [
      'Text preprocessing & tokenization',
      'Embeddings, classical NLP & evaluation metrics',
      'Sequence models & transformer architectures',
      'Fine-tuning LLMs for NLP tasks',
      'RAG, prompt engineering & guardrails',
      'NLP application architecture in production',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['Transformers', 'RAG', 'Tokenization'],
    flavorNotes: ['BLEU/ROUGE', 'Attention mechanisms', 'Hallucination mitigation'],
  },
  LARGE_LANGUAGE_MODEL_LLM_APPLICATION_ENGINEERING: {
    topics: [
      'LLM capabilities, limits & safety basics',
      'Prompt design, chaining & tool use',
      'RAG pipelines, vector stores & retrieval',
      'Fine-tuning, adapters & evaluation harnesses',
      'Latency, cost & caching strategies',
      'LLM application architecture at scale',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['RAG', 'Prompt engineering', 'Tool calling'],
    flavorNotes: ['Context windows', 'Guardrails', 'Embedding models'],
  },
  MLOPS_MODEL_LIFECYCLE_MANAGEMENT: {
    topics: [
      'MLOps principles & experiment tracking',
      'Feature stores & reproducible pipelines',
      'CI/CD for models & automated validation',
      'Model registry, promotion & rollback',
      'Production monitoring & drift detection',
      'MLOps platform architecture',
    ],
    sdeFormCode: 'SDE_DEPLOYMENT_CICD',
    taskFamily: 'APPLIED',
    focusOptions: ['MLflow', 'Kubeflow', 'Model registry'],
    flavorNotes: ['Experiment tracking', 'Model cards', 'Canary deployments'],
  },
  COMPUTER_VISION_ENGINEERING: {
    topics: [
      'Image representation, preprocessing & augmentation',
      'Classical CV: filters, features & edge detection',
      'CNN architectures, transfer learning & fine-tuning',
      'Object detection, segmentation & tracking',
      'Model evaluation metrics & deployment pipelines',
      'End-to-end computer vision system design',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['OpenCV', 'CNNs', 'Object detection'],
    flavorNotes: ['IoU/mAP metrics', 'Data augmentation', 'ONNX export'],
  },
  STATISTICAL_ANALYSIS_EXPERIMENTATION: {
    topics: [
      'Descriptive stats & probability distributions',
      'Hypothesis testing & confidence intervals',
      'Regression, ANOVA & experimental design',
      'A/B testing, power analysis & sample size',
      'Causal inference & confounding control',
      'Experimentation platform & analytics governance',
    ],
    sdeFormCode: 'SDE_PROGRAMMING_FUNDAMENTALS',
    taskFamily: 'APPLIED',
    focusOptions: ['A/B testing', 'Regression', 'Power analysis'],
    flavorNotes: ['p-values vs effect size', 'Multiple comparisons', 'Randomization'],
  },
  APPLICATION_SECURITY_APPSEC: {
    topics: [
      'OWASP Top 10 & secure SDLC basics',
      'Input validation, XSS & injection prevention',
      'Authentication, session & CSRF defenses',
      'Secure coding reviews & SAST/DAST tooling',
      'Secrets management & dependency scanning',
      'Application security architecture & threat modeling',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['OWASP', 'SAST', 'Threat modeling'],
    flavorNotes: ['SQL injection', 'SSRF', 'Security headers'],
  },
  CLOUD_SECURITY_ENGINEERING: {
    topics: [
      'Shared responsibility model & cloud threats',
      'IAM, least privilege & federation',
      'Network segmentation & WAF/cloud armor',
      'Encryption at rest/in transit & KMS',
      'CSPM, misconfiguration detection & auditing',
      'Cloud security reference architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['IAM', 'CSPM', 'Zero trust'],
    flavorNotes: ['Security groups', 'KMS rotation', 'CloudTrail'],
  },
  IDENTITY_ACCESS_MANAGEMENT_IAM: {
    topics: [
      'Identity fundamentals & directory services',
      'Authentication protocols (OAuth2, OIDC, SAML)',
      'Authorization models (RBAC, ABAC)',
      'MFA, passwordless & privileged access',
      'Identity governance & lifecycle management',
      'Enterprise IAM architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['OAuth2', 'OIDC', 'RBAC'],
    flavorNotes: ['Token lifetimes', 'Federation', 'PAM'],
  },
  PENETRATION_TESTING_VULNERABILITY_ASSESSMENT: {
    topics: [
      'Reconnaissance & vulnerability scanning',
      'Web app pentest methodology (OWASP WSTG)',
      'Network exploitation & privilege escalation',
      'Reporting, CVSS scoring & remediation guidance',
      'Red team tactics & social engineering awareness',
      'Offensive security program architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Burp Suite', 'Nmap', 'Metasploit'],
    flavorNotes: ['Scope/rules of engagement', 'Chained exploits', 'PoC reporting'],
  },
  SECURITY_OPERATIONS_INCIDENT_RESPONSE: {
    topics: [
      'SOC fundamentals & log sources',
      'SIEM rules, detection engineering & tuning',
      'Incident triage, containment & eradication',
      'Forensics basics & evidence handling',
      'Playbooks, tabletop exercises & metrics',
      'Security operations center architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['SIEM', 'Incident response', 'SOAR'],
    flavorNotes: ['MITRE ATT&CK', 'Chain of custody', 'MTTD/MTTR'],
  },
  COMPLIANCE_RISK_MANAGEMENT: {
    topics: [
      'Compliance frameworks (SOC2, ISO 27001, PCI)',
      'Risk assessment & control mapping',
      'Policy management & audit evidence collection',
      'Vendor risk & third-party assessments',
      'Continuous compliance monitoring',
      'GRC program architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['SOC2', 'ISO 27001', 'Risk registers'],
    flavorNotes: ['Control owners', 'Audit trails', 'Residual risk'],
  },
  TEST_AUTOMATION_ENGINEERING: {
    topics: [
      'Test pyramid & automation strategy',
      'Unit/integration test design patterns',
      'UI/API automation frameworks',
      'Test data management & environment isolation',
      'CI integration, flaky test triage & reporting',
      'Test automation platform architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Unit tests', 'Selenium', 'Playwright'],
    flavorNotes: ['Page objects', 'Mocking strategies', 'Test parallelism'],
  },
  PERFORMANCE_LOAD_TESTING: {
    topics: [
      'Performance testing types & objectives',
      'Workload modeling & scenario design',
      'Load/stress/soak test execution',
      'Metrics analysis & bottleneck identification',
      'Capacity planning from test results',
      'Performance engineering program design',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['JMeter', 'k6', 'Gatling'],
    flavorNotes: ['Percentiles p95/p99', 'Think time', 'Saturation points'],
  },
  CONTINUOUS_TESTING_QUALITY_ENGINEERING: {
    topics: [
      'Shift-left testing & quality gates',
      'Test orchestration in CI/CD pipelines',
      'Quality metrics & defect escape analysis',
      'Test environment provisioning & service virtualization',
      'Quality engineering coaching & standards',
      'Continuous quality platform architecture',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Quality gates', 'Shift-left', 'Test orchestration'],
    flavorNotes: ['Definition of done', 'Flake detection', 'Coverage vs risk'],
  },
  API_CONTRACT_TESTING: {
    topics: [
      'Contract testing principles & consumer-driven contracts',
      'OpenAPI/AsyncAPI schema validation',
      'Pact/provider verification workflows',
      'Breaking change detection & versioning',
      'Mock servers & contract CI integration',
      'API contract testing platform design',
    ],
    sdeFormCode: 'SDE_TESTING',
    taskFamily: 'APPLIED',
    focusOptions: ['Pact', 'OpenAPI', 'Contract tests'],
    flavorNotes: ['Provider verification', 'Schema diffing', 'Backward compatibility'],
  },
  NATIVE_ANDROID_DEVELOPMENT: {
    topics: [
      'Android fundamentals & activity/fragment lifecycle',
      'Jetpack Compose/UI layout patterns',
      'Navigation, ViewModel & state management',
      'Networking, Room & background work',
      'Testing, profiling & Play Store requirements',
      'Android app architecture (Clean/MVI)',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['Kotlin', 'Jetpack Compose', 'Room'],
    flavorNotes: ['Lifecycle observers', 'Coroutines on Android', 'Material Design'],
  },
  NATIVE_IOS_DEVELOPMENT: {
    topics: [
      'iOS app lifecycle & SwiftUI/UIKit',
      'Navigation, state & dependency injection',
      'Networking, Core Data & background tasks',
      'Accessibility, localization & HIG compliance',
      'XCTest, TestFlight & release management',
      'iOS application architecture patterns',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['SwiftUI', 'UIKit', 'Core Data'],
    flavorNotes: ['Delegate patterns', 'App extensions', 'Push notifications'],
  },
  CROSS_PLATFORM_MOBILE_DEVELOPMENT: {
    topics: [
      'Cross-platform trade-offs (RN/Flutter)',
      'Shared UI/state & platform channels',
      'Navigation, storage & native module integration',
      'Performance optimization on mobile devices',
      'Testing, OTA updates & store deployment',
      'Cross-platform mobile architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['React Native', 'Flutter', 'Expo'],
    flavorNotes: ['Bridge performance', 'Platform-specific code', 'Hermes engine'],
  },
  MODERN_FRONTEND_FRAMEWORKS: {
    topics: [
      'HTML/CSS/JS fundamentals & accessibility basics',
      'React/Vue/Angular component models',
      'Routing, forms & client-side state',
      'API integration, auth & error boundaries',
      'Testing, bundling & Core Web Vitals',
      'Frontend application architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['React', 'Vue', 'Angular'],
    flavorNotes: ['Hooks', 'Virtual DOM', 'SSR vs CSR'],
  },
  FRONTEND_PERFORMANCE_ENGINEERING: {
    topics: [
      'Core Web Vitals & performance budgets',
      'Bundle analysis, code splitting & lazy loading',
      'Rendering optimization & memoization',
      'Network waterfall, caching & CDN usage',
      'Profiling with Lighthouse & browser devtools',
      'Frontend performance architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['LCP', 'CLS', 'Code splitting'],
    flavorNotes: ['Tree shaking', 'Prefetch/preload', 'Image optimization'],
  },
  STATE_MANAGEMENT_COMPONENT_ARCHITECTURE: {
    topics: [
      'Component composition & design systems',
      'Local vs global state patterns',
      'Redux/Zustand/Context state libraries',
      'Side effects, async data & caching layers',
      'Testing components & state transitions',
      'Scalable frontend component architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'CODING',
    focusOptions: ['Redux', 'Zustand', 'Design systems'],
    flavorNotes: ['Selector memoization', 'Atomic design', 'Prop drilling avoidance'],
  },
  ACCESSIBILITY_ENGINEERING_A11Y: {
    topics: [
      'WCAG principles & assistive technology basics',
      'Semantic HTML & ARIA roles/states',
      'Keyboard navigation & focus management',
      'Color contrast, motion & inclusive design',
      'Automated/manual a11y testing tooling',
      'Accessibility program & compliance architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'APPLIED',
    focusOptions: ['WCAG 2.2', 'ARIA', 'Screen readers'],
    flavorNotes: ['Focus traps', 'Live regions', 'axe-core audits'],
  },
  NETWORK_ARCHITECTURE_PROTOCOLS: {
    topics: [
      'OSI/TCP-IP & common protocol behavior',
      'IP addressing, routing & switching',
      'DNS, DHCP & load balancing fundamentals',
      'Firewalls, VPNs & network security basics',
      'Troubleshooting connectivity & packet analysis',
      'Enterprise network architecture design',
    ],
    sdeFormCode: 'SDE_COMPUTER_NETWORKS',
    taskFamily: 'APPLIED',
    focusOptions: ['TCP/IP', 'DNS', 'Routing'],
    flavorNotes: ['Subnetting', 'NAT', 'Wireshark basics'],
  },
  LINUX_SYSTEMS_ADMINISTRATION: {
    topics: [
      'Linux filesystem, users & permissions',
      'Process management & systemd services',
      'Package management & configuration files',
      'Shell scripting & automation',
      'Monitoring, logs & performance tuning',
      'Linux server fleet architecture',
    ],
    sdeFormCode: 'SDE_OPERATING_SYSTEMS',
    taskFamily: 'APPLIED',
    focusOptions: ['systemd', 'bash', 'SSH hardening'],
    flavorNotes: ['chmod/chown', 'journalctl', 'Cron vs timers'],
  },
  VIRTUALIZATION_HYPERVISOR_MANAGEMENT: {
    topics: [
      'Virtualization concepts & hypervisor types',
      'VM provisioning, snapshots & templates',
      'Resource allocation & overcommit strategies',
      'Storage/network virtualization basics',
      'HA clusters & live migration',
      'Virtualization platform architecture',
    ],
    sdeFormCode: 'SDE_OPERATING_SYSTEMS',
    taskFamily: 'APPLIED',
    focusOptions: ['VMware', 'KVM', 'Hyper-V'],
    flavorNotes: ['vMotion', 'Resource pools', 'Thin provisioning'],
  },
  BLOCKCHAIN_SMART_CONTRACT_DEVELOPMENT: {
    topics: [
      'Blockchain fundamentals & consensus models',
      'Smart contract languages (Solidity/Rust)',
      'Token standards, wallets & transactions',
      'Security vulnerabilities & audit practices',
      'dApp frontends & oracle integration',
      'Blockchain application architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Solidity', 'Ethereum', 'Smart contracts'],
    flavorNotes: ['Reentrancy', 'Gas optimization', 'Upgrade patterns'],
  },
  INTERNET_OF_THINGS_IOT_ENGINEERING: {
    topics: [
      'IoT architecture & device connectivity',
      'Embedded protocols (MQTT, CoAP, BLE)',
      'Edge processing & firmware OTA updates',
      'IoT security, provisioning & PKI',
      'Telemetry pipelines & digital twins',
      'Industrial IoT platform design',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['MQTT', 'Edge computing', 'Device management'],
    flavorNotes: ['Device shadows', 'Firmware signing', 'Time-series ingestion'],
  },
  AUGMENTED_VIRTUAL_REALITY_DEVELOPMENT: {
    topics: [
      'XR fundamentals & hardware tracking',
      '3D math, rendering & scene graph basics',
      'Unity/Unreal XR development workflows',
      'Interaction design & spatial UX',
      'Performance optimization for headsets',
      'Immersive application architecture',
    ],
    sdeFormCode: 'SDE_WEB_FRAMEWORKS',
    taskFamily: 'APPLIED',
    focusOptions: ['Unity XR', 'OpenXR', 'Spatial UX'],
    flavorNotes: ['Frame pacing', 'Hand tracking', 'Locomotion comfort'],
  },
  EDGE_COMPUTING: {
    topics: [
      'Edge computing drivers & topology patterns',
      'Latency-sensitive workload placement',
      'Edge orchestration & offline-first sync',
      'Security & updates at the edge',
      'Observability across edge-cloud boundaries',
      'Edge platform reference architecture',
    ],
    sdeFormCode: 'SDE_SYSTEM_DESIGN',
    taskFamily: 'APPLIED',
    focusOptions: ['Edge nodes', 'Offline sync', 'K3s'],
    flavorNotes: ['Split inference', 'Store-and-forward', 'Edge gateways'],
  },
  AGILE_DELIVERY_LEADERSHIP: {
    topics: [
      'Agile values, Scrum/Kanban fundamentals',
      'Backlog refinement & sprint planning',
      'Facilitation, retrospectives & team health',
      'Metrics: velocity, flow & predictability',
      'Scaling agile (SAFe/LeSS basics)',
      'Agile transformation leadership',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Scrum', 'Kanban', 'Retrospectives'],
    flavorNotes: ['Definition of ready', 'WIP limits', 'Servant leadership'],
  },
  TECHNICAL_PROGRAM_PROJECT_MANAGEMENT: {
    topics: [
      'Project charter, scope & stakeholder mapping',
      'Scheduling, critical path & dependencies',
      'Risk/issue management & escalation',
      'Budget, resourcing & vendor coordination',
      'Status reporting & executive communication',
      'Technical program governance model',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Roadmaps', 'RAID logs', 'Stakeholders'],
    flavorNotes: ['Milestone planning', 'RACI', 'Change control'],
  },
  VERSION_CONTROL_CODE_COLLABORATION: {
    topics: [
      'Git fundamentals & branching strategies',
      'Pull requests, code review & merge policies',
      'Rebase, cherry-pick & conflict resolution',
      'Hooks, signed commits & repo hygiene',
      'Monorepo vs polyrepo collaboration patterns',
      'Engineering collaboration platform design',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Git', 'Pull requests', 'Trunk-based development'],
    flavorNotes: ['Merge vs rebase', 'Conventional commits', 'CODEOWNERS'],
  },
  TECHNICAL_DOCUMENTATION_KNOWLEDGE_MANAGEMENT: {
    topics: [
      'Documentation types & audience analysis',
      'Docs-as-code & information architecture',
      'API docs, runbooks & ADR practices',
      'Knowledge base search & discoverability',
      'Review workflows & doc quality metrics',
      'Technical writing program architecture',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['ADRs', 'Runbooks', 'Docs-as-code'],
    flavorNotes: ['Diátaxis framework', 'Single sourcing', 'Stale doc detection'],
  },
  CROSS_FUNCTIONAL_STAKEHOLDER_COLLABORATION: {
    topics: [
      'Stakeholder identification & communication plans',
      'Requirements elicitation & alignment workshops',
      'Managing conflicting priorities & trade-offs',
      'Cross-team dependencies & interface agreements',
      'Feedback loops with product/design/ops',
      'Collaboration operating model in tech orgs',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Stakeholder maps', 'Workshops', 'RACI'],
    flavorNotes: ['Expectation setting', 'Decision records', 'Escalation paths'],
  },
  MENTORSHIP_TECHNICAL_LEADERSHIP: {
    topics: [
      'Technical leadership roles & influence without authority',
      'Mentoring models & growth plans for engineers',
      'Architecture decision facilitation & RFCs',
      'Hiring loops, interviews & bar raising',
      'Psychological safety & feedback culture',
      'Engineering leadership & org design basics',
    ],
    sdeFormCode: 'SDE_GIT',
    taskFamily: 'APPLIED',
    focusOptions: ['Mentorship', 'RFCs', 'Career growth'],
    flavorNotes: ['Situational leadership', 'Promotion packets', 'Tech vision'],
  },
};
