/**
 * Sprint 0 backlog — Foundation & Contracts (AGILE_PLAN.md §7).
 */
import { formatStoryDescription } from '../backlog/format.mjs';

export { formatStoryDescription };

export const SPRINT = {
  name: 'Sprint 0 — Foundation & Contracts (21–23 Aug 2026)',
  startdate: '2026-08-21T00:00:00+05:30',
  enddate: '2026-08-23T23:59:59+05:30',
  description: `**Goal:** All 6 engineers running the full stack locally; contracts v0.1 merged and frozen.

**Exit criteria:** \`git clone && ./scripts/bootstrap.sh && pnpm dev\` brings up 4 web apps + API + infra; \`GET /api/v1/catalog/tracks\` returns 10 tracks; \`pnpm test\` green; contracts v0.1 tagged.`,
};

export const EPICS = [
  {
    key: 'E0T',
    name: 'E0 — Repo, Contracts & Governance',
    owner: 'Tino',
    color: '#64748b',
    desc: 'Monorepo scaffold, @smart/contracts v0.1, CI/CODEOWNERS, ADRs. Owner: Tino.',
  },
  {
    key: 'E0V',
    name: 'E0 — Infra & API Bootstrap',
    owner: 'Vishal V',
    color: '#2563eb',
    desc: 'Docker data plane, NestJS bootstrap, Prisma schema v1, bootstrap script. Owner: Vishal V.',
  },
  {
    key: 'E0S',
    name: 'E0 — Frontend Foundation',
    owner: 'Satheswaran V',
    color: '#7c3aed',
    desc: 'packages/ui scaffold, four Next.js apps, api-client. Owner: Satheswaran V.',
  },
  {
    key: 'E0B',
    name: 'E0 — Module & Admin Shells',
    owner: 'Vishal Bharath R',
    color: '#059669',
    desc: 'api-core module skeletons, web-verify and web-admin layouts. Owner: Vishal Bharath R.',
  },
  {
    key: 'E0R',
    name: 'E0 — AI & Scoring Foundation',
    owner: 'Ramansh',
    color: '#d97706',
    desc: 'scoring-engine scaffold, ai-gateway skeleton with dual providers. Owner: Ramansh.',
  },
  {
    key: 'E0G',
    name: 'E0 — Content Pipeline & Catalog Seed',
    owner: 'Vedika G',
    color: '#db2777',
    desc: 'content-pipeline CLI, catalog seed (10 tracks / 50 competencies / 50 levels). Owner: Vedika G.',
  },
];

const DOD_ALL = [
  'Acceptance criteria met and demoed on develop (or curl/screenshot in PR)',
  'pnpm lint, typecheck, build, test:unit green in CI',
  'Conventional commit + PR title includes ticket ID',
  'PR ≤ 400 LOC; Tino approved; squash-merged to develop',
];

const DOD_BACKEND = [
  'Types/DTOs in @smart/contracts if cross-module; Zod validation at boundary',
  'Unit + integration tests (DB/Redis/Kafka stubbed as needed)',
  'Module README updated if new surface area',
  'No secrets in code',
];

const DOD_FRONTEND = [
  'Typed via @smart/api-client or @smart/ui tokens — no raw fetch in apps',
  'Component renders without console errors',
];

const DOD_INFRA = ['Documented in LOCAL_DEV.md or README', 'Healthchecks pass in docker compose'];

const DOD_CONTRACTS = [
  'Breaking changes versioned in @smart/contracts',
  'Kafka payloads match ARCHITECTURE event names',
];

const DOD_AI = ['Unit tests for pure functions', 'Config keys documented in .env.example'];

const DOD_DATA = [
  'Seed idempotent — safe to re-run bootstrap',
  'Validation wired in CI where applicable',
];

const SPRINT_GOAL =
  'All 6 engineers unblocked locally; contracts v0.1 frozen; bootstrap one-command green.';

function story(base) {
  const typeDod =
    base.type === 'frontend'
      ? DOD_FRONTEND
      : base.type === 'infra'
        ? DOD_INFRA
        : base.type === 'contracts'
          ? DOD_CONTRACTS
          : base.type === 'ai'
            ? DOD_AI
            : base.type === 'data'
              ? DOD_DATA
              : DOD_BACKEND;
  return {
    sprintGoalLink: SPRINT_GOAL,
    dod: [...DOD_ALL, ...typeDod],
    ...base,
  };
}

export const STORIES = [
  story({
    id: 'S0-TN-01',
    epic: 'E0T',
    github: 0,
    title: 'Monorepo scaffold, workspace graph, turbo.json, shared tsconfig/eslint/prettier',
    owner: 'Tino',
    handle: '@brittytino',
    points: 5,
    priority: 'P0',
    area: 'area:infra',
    type: 'infra',
    userValue:
      'Every engineer clones one repo with consistent tooling and fast incremental builds.',
    contractImpact: 'none — repo layout only',
    blockedBy: [],
    blocks: ['S0-TN-02', 'S0-TN-03', 'S0-VV-02', 'S0-SV-01', 'S0-RM-01', 'S0-VG-01'],
    acceptanceCriteria: [
      'pnpm workspace with apps/* and packages/*',
      'turbo.json pipelines: lint, typecheck, build, test',
      'Shared tsconfig, eslint, prettier configs',
      'Root scripts: dev, build, test, lint',
    ],
    failureModes: ['Broken workspace graph fails CI on PR'],
    demoScript: 'pnpm install && pnpm build && pnpm lint at repo root.',
    subtasks: [
      'pnpm-workspace.yaml',
      'turbo.json',
      'packages/config-*',
      'Root package.json scripts',
    ],
  }),
  story({
    id: 'S0-TN-02',
    epic: 'E0T',
    github: 0,
    title: '@smart/contracts v0.1: enums, attempt/certificate DTOs, 8 Kafka event payloads',
    owner: 'Tino',
    handle: '@brittytino',
    points: 5,
    priority: 'P0',
    area: 'area:contracts',
    type: 'contracts',
    userValue: 'Cross-module types are contract-first — no duplicate DTOs in apps.',
    contractImpact: 'This IS the contracts package v0.1',
    blockedBy: ['S0-TN-01'],
    blocks: ['S0-VB-01', 'S0-SV-03', 'S0-VV-07'],
    acceptanceCriteria: [
      'Tier/level/track/role enums exported',
      'Attempt & certificate DTOs with Zod schemas',
      'All 8 Kafka event payload types from ARCHITECTURE',
      'Package builds and is consumed by api-core',
    ],
    failureModes: ['Drift between event names and ARCHITECTURE §events'],
    demoScript: 'import from @smart/contracts in api-core; pnpm typecheck green.',
    subtasks: ['Enum modules', 'DTO + Zod pairs', 'Kafka payload types', 'v0.1 tag'],
  }),
  story({
    id: 'S0-TN-03',
    epic: 'E0T',
    github: 0,
    title: 'CODEOWNERS, branch protection, PR/issue templates, CI pipeline',
    owner: 'Tino',
    handle: '@brittytino',
    points: 3,
    priority: 'P0',
    area: 'area:infra',
    type: 'infra',
    userValue: 'Quality gates and review workflow are enforced before feature work.',
    contractImpact: 'none',
    blockedBy: ['S0-TN-01'],
    blocks: [],
    acceptanceCriteria: [
      'CODEOWNERS with module owners + mandatory @brittytino',
      'Branch protection on develop (reviews, status checks)',
      'PR and issue templates',
      'CI: lint → typecheck → test → build',
    ],
    failureModes: ['CI flaky blocks all merges'],
    demoScript: 'Open PR → CI runs; merge blocked without review.',
    subtasks: ['.github/CODEOWNERS', 'workflow yaml', 'templates', 'branch protection doc'],
  }),
  story({
    id: 'S0-TN-04',
    epic: 'E0T',
    github: 0,
    title: 'ADR-0001…0008: stack, contracts, boundaries, AI failover, rate limits',
    owner: 'Tino',
    handle: '@brittytino',
    points: 3,
    priority: 'P1',
    area: 'area:infra',
    type: 'infra',
    userValue: 'Architectural decisions are recorded — reviewers have a single source of truth.',
    contractImpact: 'none',
    blockedBy: ['S0-TN-01'],
    blocks: [],
    acceptanceCriteria: [
      'ADRs 0001–0008 in docs/adr/',
      'Covers stack, pnpm, contract-first, module boundaries',
      'AI failover and tier authority documented',
      'Migration stewardship + rate-limit strategy',
    ],
    failureModes: ['ADR contradicts ARCHITECTURE.md'],
    demoScript: 'docs/adr/ lists 8 accepted ADRs linked from README.',
    subtasks: ['ADR template', '0001 stack', '0002–0008 topics', 'Index in README'],
  }),
  story({
    id: 'S0-VV-01',
    epic: 'E0V',
    github: 0,
    title:
      'docker-compose: Postgres 17+pgvector, Redis 7, Redpanda, MinIO, Mailpit, observability stack',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:infra',
    type: 'infra',
    userValue: 'Local data plane matches production topology — engineers run real infra locally.',
    contractImpact: 'none',
    blockedBy: ['S0-TN-01'],
    blocks: ['S0-VV-02', 'S0-VV-03', 'S0-VV-04'],
    acceptanceCriteria: [
      'infra/docker/docker-compose.yml with all services',
      'Postgres 17 + pgvector extension',
      'Redis 7, Redpanda, MinIO, Mailpit',
      'Prometheus, Grafana, Loki with healthchecks',
    ],
    failureModes: ['Port conflicts documented in LOCAL_DEV.md'],
    demoScript: 'docker compose up -d → all services healthy.',
    subtasks: ['compose file', 'Healthchecks', 'Volume mounts', 'LOCAL_DEV.md ports table'],
  }),
  story({
    id: 'S0-VV-02',
    epic: 'E0V',
    github: 0,
    title: 'api-core NestJS 11 + Fastify bootstrap: config, pino, Swagger, /health + /ready',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'API server boots with validated config, logging, and probes every module will use.',
    contractImpact: 'Health DTOs if shared',
    blockedBy: ['S0-TN-01', 'S0-VV-01'],
    blocks: ['S0-VV-03', 'S0-VV-04', 'S0-VB-01', 'S0-VG-02'],
    acceptanceCriteria: [
      'NestJS 11 + Fastify adapter',
      'Zod-validated config module',
      'Pino structured logging',
      'Swagger at /api/docs',
      'GET /health and /ready (Postgres + Redis)',
    ],
    failureModes: ['Missing env fails fast with clear error'],
    demoScript: 'pnpm dev:api → /health 200, /ready 200, /api/docs loads.',
    subtasks: ['main.ts + app.module', 'Config module', 'Health module', 'Swagger setup'],
  }),
  story({
    id: 'S0-VV-03',
    epic: 'E0V',
    github: 0,
    title: 'Prisma 7 schema v1 — all 14 tables from ARCHITECTURE §5 + pgvector; first migration',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Database schema exists — all Sprint 1+ features build on this foundation.',
    contractImpact: 'Schema aligns with contracts enums',
    blockedBy: ['S0-VV-01', 'S0-VV-02'],
    blocks: ['S0-VV-04', 'S0-VG-02', 'S1-VV-01'],
    acceptanceCriteria: [
      'All 14 tables from ARCHITECTURE.md §5',
      'pgvector column where specified',
      'First migration applied via prisma migrate',
      'prisma generate in CI',
    ],
    failureModes: ['Migration not forward-only'],
    demoScript: 'pnpm prisma migrate deploy → schema matches ERD.',
    subtasks: ['schema.prisma', 'Initial migration', 'Seed hook stub', 'CI migrate step'],
  }),
  story({
    id: 'S0-VV-04',
    epic: 'E0V',
    github: 0,
    title: 'scripts/bootstrap.sh — one command to working local env; documented in README',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 3,
    priority: 'P0',
    area: 'area:infra',
    type: 'infra',
    userValue: 'New engineer runs one command and is unblocked — Sprint 0 exit criterion.',
    contractImpact: 'none',
    blockedBy: ['S0-VV-01', 'S0-VV-02', 'S0-VV-03', 'S0-VG-02'],
    blocks: ['S1-VV-01'],
    acceptanceCriteria: [
      './scripts/bootstrap.sh: install → compose up → migrate → seed',
      'Documented in README and LOCAL_DEV.md',
      'Windows path documented (manual steps or Git Bash)',
      'verify-handover.sh passes after bootstrap',
    ],
    failureModes: ['Partial failure leaves dirty state — script exits non-zero'],
    demoScript: 'Fresh clone → ./scripts/bootstrap.sh → pnpm dev works.',
    subtasks: ['bootstrap.sh', 'pnpm bootstrap alias', 'LOCAL_DEV.md', 'verify-handover.sh'],
  }),
  story({
    id: 'S0-SV-01',
    epic: 'E0S',
    github: 0,
    title: 'packages/ui scaffold: Tailwind 4 tokens, dark theme, Button/Card/Badge/TierBadge',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 5,
    priority: 'P0',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Shared design system primitives — four apps look like one product.',
    contractImpact: 'Tier types from contracts for TierBadge',
    blockedBy: ['S0-TN-01'],
    blocks: ['S0-SV-02'],
    acceptanceCriteria: [
      'Tailwind 4 + design tokens',
      'Dark theme default',
      'Button, Card, Badge, TierBadge exported',
      'Package builds standalone',
    ],
    failureModes: ['Token drift between apps'],
    demoScript: 'Import Button + TierBadge in Storybook or test page.',
    subtasks: ['Tailwind config', 'Token CSS vars', 'Four primitives', 'Package exports'],
  }),
  story({
    id: 'S0-SV-02',
    epic: 'E0S',
    github: 0,
    title: 'Four Next.js 16 apps on shared config, @smart/ui, live /health probe',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 5,
    priority: 'P0',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'All four portals boot and prove connectivity — student, TPO, admin, verify.',
    contractImpact: 'none',
    blockedBy: ['S0-SV-01'],
    blocks: ['S0-VB-02', 'S0-VV-04'],
    acceptanceCriteria: [
      'web-student, web-tpo, web-admin, web-verify scaffolded',
      'Shared Next config from packages',
      'Each app consumes @smart/ui',
      'Each renders /health or home probe on :3001–3004',
    ],
    failureModes: ['Port collision with api-core documented'],
    demoScript: 'pnpm dev → four apps load on 3001–3004.',
    subtasks: ['App scaffolds', 'Shared next config', 'Health pages', 'turbo dev pipeline'],
  }),
  story({
    id: 'S0-SV-03',
    epic: 'E0S',
    github: 0,
    title: 'packages/api-client: typed fetch, TanStack Query, 401 refresh, 429 backoff',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 3,
    priority: 'P1',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Frontend never uses raw fetch — typed client with auth and rate-limit handling.',
    contractImpact: 'Consumes @smart/contracts DTOs',
    blockedBy: ['S0-TN-02'],
    blocks: ['S1-SV-01'],
    acceptanceCriteria: [
      'Typed fetch wrapper over contracts',
      'TanStack Query provider export',
      '401 triggers silent refresh hook (stub ok for S0)',
      '429 reads Retry-After and backs off',
    ],
    failureModes: ['Refresh loop on bad token'],
    demoScript: 'Hook calls GET /health with typed response.',
    subtasks: ['fetch wrapper', 'Query provider', '401 interceptor stub', '429 backoff util'],
  }),
  story({
    id: 'S0-VB-01',
    epic: 'E0B',
    github: 0,
    title: 'api-core module skeletons: assessment, certificate, webhooks + Swagger tags',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 3,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Module boundaries exist before Sprint 1 feature work — no monolith sprawl.',
    contractImpact: 'Swagger tags match module names',
    blockedBy: ['S0-VV-02', 'S0-TN-02'],
    blocks: ['S1-VB-01'],
    acceptanceCriteria: [
      'Nest modules: assessment, certificate, webhooks',
      'Owner headers in module README',
      'Swagger tags per module',
      'Placeholder controllers return 501 or health',
    ],
    failureModes: ['Cross-module imports in skeleton'],
    demoScript: 'Swagger shows three module tag groups.',
    subtasks: [
      'Module folders',
      'Swagger decorators',
      'README owner headers',
      'app.module imports',
    ],
  }),
  story({
    id: 'S0-VB-02',
    epic: 'E0B',
    github: 0,
    title: 'web-verify + web-admin routing shells and layouts',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 3,
    priority: 'P1',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Trust and admin surfaces have navigation shells ready for Sprint 1+ features.',
    contractImpact: 'none',
    blockedBy: ['S0-SV-02'],
    blocks: ['S1-VB-04'],
    acceptanceCriteria: [
      'web-verify layout with public chrome',
      'web-admin layout with sidebar nav',
      'Routing structure documented',
      'Uses @smart/ui primitives',
    ],
    failureModes: ['Layout shift on navigation'],
    demoScript: 'Admin sidebar renders; verify landing page loads.',
    subtasks: ['Admin layout', 'Verify layout', 'Nav config', 'Placeholder routes'],
  }),
  story({
    id: 'S0-RM-01',
    epic: 'E0R',
    github: 0,
    title: 'scoring-engine: assignTier, Angoff, cohensKappa, cronbachAlpha + unit tests',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 5,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'Psychometric primitives are tested before AI grading depends on them.',
    contractImpact: 'Tier enums from contracts',
    blockedBy: ['S0-TN-01'],
    blocks: ['S1-VG-02'],
    acceptanceCriteria: [
      'Effect.ts scaffold in packages/scoring-engine',
      'assignTier, deriveAngoffCutScore implemented',
      'cohensKappa, cronbachAlpha with unit tests',
      'Package builds independently',
    ],
    failureModes: ['NaN on empty panel input'],
    demoScript: 'pnpm test --filter scoring-engine green.',
    subtasks: ['Package scaffold', 'Core functions', 'Unit tests', 'Export API'],
  }),
  story({
    id: 'S0-RM-02',
    epic: 'E0R',
    github: 0,
    title: 'ai-gateway skeleton: Anthropic + Google clients, /ai/health dual-provider report',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 5,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'AI boundary exists before Sprint 1 failover work — keys validated at boot.',
    contractImpact: 'none',
    blockedBy: ['S0-TN-01'],
    blocks: ['S1-RM-01', 'S1-RM-02'],
    acceptanceCriteria: [
      'Single interface over Anthropic + Google SDKs',
      'Keys from validated config / .env.example',
      'GET /ai/health reports both provider reachability',
      'No direct LLM calls outside gateway package',
    ],
    failureModes: ['Missing key fails health with clear status'],
    demoScript: '/ai/health returns provider status JSON.',
    subtasks: ['Gateway interface', 'Provider adapters', 'Health endpoint', '.env.example keys'],
  }),
  story({
    id: 'S0-VG-01',
    epic: 'E0G',
    github: 0,
    title: 'content-pipeline CLI scaffold + item JSON schema + validate in CI',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 5,
    priority: 'P0',
    area: 'area:data',
    type: 'data',
    userValue: 'Content authoring is validated in CI before bad items reach the catalog.',
    contractImpact: 'Item schema aligns with catalog DTOs',
    blockedBy: ['S0-TN-01'],
    blocks: ['S0-VG-02', 'S1-VG-01'],
    acceptanceCriteria: [
      'tools/content-pipeline CLI entry',
      'Item authoring JSON schema',
      'validate command exits non-zero on bad files',
      'Wired into CI on content paths',
    ],
    failureModes: ['Schema too loose — invalid items pass'],
    demoScript: 'pnpm content validate → green on seed fixtures.',
    subtasks: ['CLI scaffold', 'JSON schema', 'validate command', 'CI job'],
  }),
  story({
    id: 'S0-VG-02',
    epic: 'E0G',
    github: 0,
    title: 'Seed 10 tracks, 50 competencies, 50 levels; GET /catalog/tracks returns them',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 5,
    priority: 'P0',
    area: 'area:data',
    type: 'data',
    userValue:
      'Catalog API returns real seed data — bootstrap exit criterion and Sprint 1 dependency.',
    contractImpact: 'Track/competency DTOs from contracts',
    blockedBy: ['S0-VV-03', 'S0-VG-01'],
    blocks: ['S0-VV-04', 'S1-SV-01'],
    acceptanceCriteria: [
      'Prisma seed: 10 tracks, 50 competencies (A–E), 50 levels',
      'GET /api/v1/catalog/tracks returns 10 tracks',
      'Seed idempotent',
      'Documented in bootstrap flow',
    ],
    failureModes: ['Duplicate seed on re-run'],
    demoScript: 'After bootstrap: curl /api/v1/catalog/tracks → 10 items.',
    subtasks: ['seed.ts', 'catalog module read endpoint', 'Fixture data', 'Integration test'],
  }),
];
