/**
 * Sprint 1 backlog — source for GitHub Issues + historical Zoho import.
 * Authority: docs/delivery/AGILE_PLAN.md §8, TEAM.md, DEFINITION_OF_DONE.md
 */
import { formatStoryDescription } from '../backlog/format.mjs';

export { formatStoryDescription };

export const SPRINT = {
  name: 'Sprint 1 — Platform Core (24–28 Aug 2026)',
  startdate: '2026-08-24T00:00:00+05:30',
  enddate: '2026-08-28T23:59:59+05:30',
  description: `**Goal:** A student logs in via SSO, is enrolled on a track, and receives real items through a rate-limited API; the AI gateway answers with Gemini failover proven.

**Exit criteria:**
- SSO login works end-to-end
- L1 attempt starts and serves items under 50 ms
- Flood test returns 429 with correct headers
- Killing Anthropic key still returns graded result via Gemini
- Finance + Business Analytics have published cut scores in DB`,
};

export const EPICS = [
  {
    key: 'E1',
    name: 'E1 — Platform Core: Identity, Limits & Events',
    owner: 'Vishal V',
    color: '#2563eb',
    desc: 'Bounded context: auth, users, rate-limit, Kafka/outbox, B2B API keys. Owner: Vishal V (platform core).',
  },
  {
    key: 'E2',
    name: 'E2 — Experience Layer: Student Portal',
    owner: 'Satheswaran V',
    color: '#7c3aed',
    desc: 'Student auth UI, dashboard shell, @smart/ui v1 components. Owner: Satheswaran V.',
  },
  {
    key: 'E3',
    name: 'E3 — Assessment Lifecycle: Start & Serve Items',
    owner: 'Vishal Bharath R',
    color: '#059669',
    desc: 'Attempt start, next-item cache, L1 submit path, admin console shell. Owner: Vishal Bharath R.',
  },
  {
    key: 'E4',
    name: 'E4 — AI Gateway & Vector Foundation',
    owner: 'Ramansh',
    color: '#d97706',
    desc: 'AI gateway quotas, Gemini failover, pgvector, evaluation audits. Owner: Ramansh.',
  },
  {
    key: 'E5',
    name: 'E5 — Content, Calibration & Catalog',
    owner: 'Vedika G',
    color: '#db2777',
    desc: 'Item banks, calibration, catalog selectors, content-pipeline embed. Owner: Vedika G.',
  },
];

const DOD_ALL = [
  'Acceptance criteria met and demoed on develop (or curl/screenshot in PR)',
  'pnpm lint, typecheck, build, test:unit green in CI',
  'Conventional commit + PR title includes ticket ID',
  'PR ≤ 400 LOC; Tino approved; squash-merged to develop',
];

const DOD_BACKEND = [
  'Types/DTOs in @smart/contracts if cross-module; Zod validation at boundary',
  'Unit + integration tests (DB/Redis/Kafka stubbed as needed)',
  'RBAC + rate-limit tier declared; Swagger on new endpoints',
  'Structured logs with traceId; Prometheus metric for new path',
  'No secrets in code; Redis keys have TTL',
];

const DOD_FRONTEND = [
  'Typed via @smart/api-client — no raw fetch',
  'Component tests or story where applicable',
  'WCAG considerations for interactive flows',
];

const DOD_AI = [
  'LLM calls only through ai-gateway; audit row on every call',
  'Integration test stubs providers; failover path tested where applicable',
];

function story(base) {
  return {
    sprintGoalLink:
      'SSO login + enrolled student receives items via rate-limited API; AI gateway with Gemini failover.',
    dod: [
      ...DOD_ALL,
      ...(base.type === 'frontend' ? DOD_FRONTEND : base.type === 'ai' ? DOD_AI : DOD_BACKEND),
    ],
    ...base,
  };
}

export const STORIES = [
  story({
    id: 'S1-VV-01',
    epic: 'E1',
    github: 3,
    title: '15-min access JWT + HttpOnly SameSite=Strict refresh rotation with reuse detection',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue:
      'Students and staff get secure sessions with short-lived access tokens and safe refresh rotation.',
    contractImpact: 'Auth DTOs in @smart/contracts — merge contract PR first if changed.',
    blockedBy: [],
    blocks: ['S1-VV-02', 'S1-VV-07', 'S1-SV-01'],
    acceptanceCriteria: [
      'Access JWT TTL = 15 minutes',
      'Refresh token in HttpOnly, SameSite=Strict cookie',
      'Refresh rotation on each use; reuse detection invalidates family',
      'Login + refresh + logout flows covered by integration test',
    ],
    failureModes: [
      'Expired refresh returns 401',
      'Reuse of old refresh revokes session',
      'Missing cookie does not crash handler',
    ],
    demoScript:
      'POST /api/v1/auth/login → access token; refresh cookie set; call refresh twice — second old token fails.',
    subtasks: [
      'Prisma: refresh token store + reuse detection fields',
      'auth.service: issue/rotate/revoke refresh tokens',
      'JWT guard + @Public() audit on auth routes',
      'Unit tests: rotation, reuse, expiry',
      'Integration test: login → refresh → reuse blocked',
      'Swagger: auth endpoints documented',
    ],
  }),
  story({
    id: 'S1-VV-02',
    epic: 'E1',
    github: 4,
    title:
      'RBAC guards + decorators: SUPER_ADMIN, INSTITUTION_ADMIN, PLACEMENT_STAFF, STUDENT, PUBLIC',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 3,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Every endpoint enforces role-based access with no implicitly public routes.',
    contractImpact: 'Role enum in @smart/contracts',
    blockedBy: ['S1-VV-01'],
    blocks: ['S1-VV-03', 'S1-VV-04', 'S1-VV-06', 'S1-VB-01'],
    acceptanceCriteria: [
      'Guards for all five roles wired globally',
      '@Roles() decorator on protected controllers',
      '@Public() only on documented public routes',
      '403 with consistent error body for wrong role',
    ],
    failureModes: ['Missing decorator defaults to deny', 'PUBLIC role cannot access admin routes'],
    demoScript: 'STUDENT token cannot hit admin route; returns 403.',
    subtasks: [
      'Roles decorator + metadata',
      'JwtAuthGuard reads roles',
      'Apply to all modules audit',
      'Unit tests per role matrix slice',
    ],
  }),
  story({
    id: 'S1-VV-03',
    epic: 'E1',
    github: 5,
    title:
      'OAuth (Google, GitHub) + SAML 2.0/OIDC institutional SSO with domain→institution mapping',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 8,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Students sign in with institutional SSO; domain maps to the correct institution.',
    contractImpact: 'Auth callback DTOs; institution mapping',
    blockedBy: ['S1-VV-02'],
    blocks: ['S1-SV-01'],
    acceptanceCriteria: [
      'Google + GitHub OAuth works locally',
      'SAML/OIDC path for institutional IdP',
      'Email domain → institution mapping persisted',
      'End-to-end: OAuth login creates/links user with STUDENT role',
    ],
    failureModes: ['Unknown domain rejected with clear error', 'IdP metadata misconfig surfaced'],
    demoScript: 'OAuth login as student@smart.local → JWT + institution attached.',
    subtasks: [
      'OAuth client + callback routes',
      'SAML/OIDC strategy module',
      'Domain→institution resolver',
      'User provisioning on first login',
      'Integration tests with mocked IdP',
      'Env: document required secrets in LOCAL_DEV',
    ],
  }),
  story({
    id: 'S1-VV-04',
    epic: 'E1',
    github: 6,
    title:
      'Redis sliding-window + token-bucket Lua guard; X-RateLimit-* + Retry-After; 429 body per §4.2',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'API stays stable under abuse; clients get standard rate-limit headers.',
    contractImpact: 'RATE_LIMIT_HEADERS + 429 body in @smart/contracts',
    blockedBy: ['S1-VV-02'],
    blocks: ['S1-VV-05', 'S1-VB-02'],
    acceptanceCriteria: [
      'Sliding-window Lua script in Redis',
      'X-RateLimit-Limit, Remaining, Reset on responses',
      '429 + Retry-After on exceed',
      'Flood integration test proves 429',
    ],
    failureModes: [
      'Redis down: dev fail-open, prod fail-closed per policy',
      'Anonymous IP bucket works',
    ],
    demoScript: 'Burst requests → 429 with Retry-After.',
    subtasks: [
      'Lua script + rate-limit.service',
      'Interceptor applies to matched routes',
      'Integration flood test',
      'Metrics: rate_limit_rejections',
    ],
  }),
  story({
    id: 'S1-VV-05',
    epic: 'E1',
    github: 7,
    title: 'Full endpoint throttle matrix from ARCHITECTURE.md §4.4 as declarative config',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 3,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Every endpoint has an explicit limit tier — no unlimited routes.',
    contractImpact: 'ROUTES rateLimit keys in @smart/contracts',
    blockedBy: ['S1-VV-04'],
    blocks: [],
    acceptanceCriteria: [
      'All ARCHITECTURE §4.4 endpoints mapped to policy keys',
      'Config is declarative (not hardcoded per controller)',
      'CI test: every registered route has a limit tier',
    ],
    failureModes: ['New route without tier fails CI or lint rule'],
    demoScript: 'Show matrix file + sample endpoint headers match tier.',
    subtasks: [
      'Declarative matrix module',
      'Wire matchContractRoute to policies',
      'Snapshot test for route coverage',
    ],
  }),
  story({
    id: 'S1-VV-06',
    epic: 'E1',
    github: 8,
    title: 'B2B X-SMART-API-KEY auth + per-key quota (500/hour) + key issuance admin API',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P1',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Institutions integrate via API keys with enforced quotas.',
    contractImpact: 'B2B auth headers DTO',
    blockedBy: ['S1-VV-02'],
    blocks: [],
    acceptanceCriteria: [
      'API key guard',
      '500 req/hour per key',
      'Admin endpoint to issue/revoke keys',
    ],
    failureModes: ['Revoked key rejected', 'Quota exceeded returns 429'],
    demoScript: 'Issue key → call API → exceed quota → 429.',
    subtasks: [
      'Prisma api_keys table',
      'Guard + quota counter in Redis',
      'Admin CRUD endpoints',
      'Tests',
    ],
  }),
  story({
    id: 'S1-VV-07',
    epic: 'E1',
    github: 9,
    title:
      'Kafka producer/consumer base + outbox pattern + DLQ; all 8 topics registered from contracts',
    owner: 'Vishal V',
    handle: '@vis465',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Reliable async events across modules with outbox and dead-letter handling.',
    contractImpact: 'All 8 Kafka payloads in @smart/contracts',
    blockedBy: ['S1-VV-01'],
    blocks: [],
    acceptanceCriteria: [
      'Producer + consumer base classes',
      'Transactional outbox write',
      'DLQ topic for poison messages',
      '8 topics registered matching contracts',
    ],
    failureModes: ['Outbox retry on broker blip', 'DLQ receives bad payload'],
    demoScript: 'Publish test event → consumer receives; bad message → DLQ.',
    subtasks: [
      'Kafka module wiring',
      'Outbox table + relay worker',
      'DLQ handler',
      'Contract topic registry test',
    ],
  }),
  story({
    id: 'S1-SV-01',
    epic: 'E2',
    github: 10,
    title: 'Student auth flow UI: SSO buttons, institution picker, track enrollment wizard',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 5,
    priority: 'P0',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Students complete login and enroll on a track through a guided UI.',
    contractImpact: 'Uses auth + enrollment API from contracts',
    blockedBy: ['S1-VV-03'],
    blocks: ['S1-SV-02'],
    acceptanceCriteria: [
      'SSO buttons trigger backend OAuth',
      'Institution picker when multiple domains',
      'Track enrollment wizard completes enrollment',
      'Errors shown inline; no silent failures',
    ],
    failureModes: ['OAuth cancel returns to login', 'Network error retry'],
    demoScript: 'web-student: login → pick track → land on dashboard shell.',
    subtasks: [
      'Login page + SSO buttons',
      'Institution picker component',
      'Enrollment wizard steps',
      'Wire @smart/api-client hooks',
      'E2E smoke (manual checklist)',
    ],
  }),
  story({
    id: 'S1-SV-02',
    epic: 'E2',
    github: 11,
    title: 'Student dashboard shell: level stepper, tier trail, next-action card',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 5,
    priority: 'P0',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Students see progress and next step at a glance.',
    contractImpact: 'Catalog/track DTOs',
    blockedBy: ['S1-SV-03', 'S1-SV-01'],
    blocks: [],
    acceptanceCriteria: [
      'LevelStepper shows L1–L5',
      'TierTrail shows tier history',
      'Next-action card from API state',
    ],
    failureModes: ['Empty state for new enrollee'],
    demoScript: 'Dashboard renders with mock/real track data.',
    subtasks: [
      'Dashboard layout',
      'Integrate TierTrail + LevelStepper from ui',
      'Next-action card',
      'Loading/error states',
    ],
  }),
  story({
    id: 'S1-SV-03',
    epic: 'E2',
    github: 12,
    title:
      'packages/ui v1: TierTrail, ConfidenceNote, LevelStepper, Timer, CodeEditor shell, AudioRecorder shell',
    owner: 'Satheswaran V',
    handle: '@Satheshwaran26',
    points: 8,
    priority: 'P0',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Shared UI primitives for assessment experience across apps.',
    contractImpact: 'Tier/level types from @smart/contracts',
    blockedBy: [],
    blocks: ['S1-SV-02'],
    acceptanceCriteria: [
      'Six components exported from @smart/ui',
      'Tailwind tokens consistent with design system',
      'Timer shell server-authoritative ready',
      'Storybook or visual test for each component',
    ],
    failureModes: ['Components work without API (props-driven)'],
    demoScript: 'Import each component in web-student page stub.',
    subtasks: [
      'TierTrail',
      'ConfidenceNote',
      'LevelStepper',
      'Timer shell',
      'CodeEditor shell',
      'AudioRecorder shell',
    ],
  }),
  story({
    id: 'S1-VB-01',
    epic: 'E3',
    github: 13,
    title:
      'POST /assessment/start — attempt row + Redis session + level unlock gate (Bronze-or-above)',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Students can start an attempt when level unlock rules pass.',
    contractImpact: 'Assessment start DTO',
    blockedBy: ['S1-VV-02'],
    blocks: ['S1-VB-02', 'S1-VB-03'],
    acceptanceCriteria: [
      'Creates attempt row in Postgres',
      'Redis session session:assessment:{id}',
      'Bronze-or-above gate enforced',
      'Returns attempt id + session metadata',
    ],
    failureModes: ['Locked level returns 403', 'Duplicate start policy documented'],
    demoScript: 'POST start → 201 + attempt id; locked level → 403.',
    subtasks: [
      'assessment.service start()',
      'Redis session schema',
      'Unlock gate logic',
      'Integration test',
    ],
  }),
  story({
    id: 'S1-VB-02',
    epic: 'E3',
    github: 14,
    title: 'GET /assessment/next-item from items:form:* warm cache, < 50 ms, zero DB hit',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'Item delivery is fast enough for interactive assessment.',
    contractImpact: 'Next-item response DTO',
    blockedBy: ['S1-VB-01', 'S1-VG-01', 'S1-VV-04'],
    blocks: ['S1-VB-03'],
    acceptanceCriteria: [
      'Served from Redis warm cache items:form:*',
      'p95 < 50 ms in local benchmark',
      'No Postgres query on hot path',
      'Respects rate limits',
    ],
    failureModes: ['Cache miss fallback defined', 'Empty bank returns 404'],
    demoScript: 'Start attempt → next-item < 50ms (logged).',
    subtasks: ['Cache key design', 'next-item handler', 'Benchmark test', 'Cache warm on start'],
  }),
  story({
    id: 'S1-VB-03',
    epic: 'E3',
    github: 15,
    title: 'POST /assessment/submit-l1 draft write-through to Redis + 5 s batch flush to Postgres',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 5,
    priority: 'P0',
    area: 'area:backend',
    type: 'backend',
    userValue: 'L1 answers autosave without losing work on refresh.',
    contractImpact: 'Submit L1 draft DTO',
    blockedBy: ['S1-VB-02'],
    blocks: [],
    acceptanceCriteria: [
      'Draft written to Redis immediately',
      'Batch flush to Postgres every 5s',
      'Resume after refresh returns same draft',
    ],
    failureModes: ['Redis down: defined degradation', 'Flush failure retried'],
    demoScript: 'Submit draft → refresh → draft still present.',
    subtasks: [
      'Redis draft schema',
      'Flush worker/batch',
      'submit-l1 endpoint',
      'Integration test',
    ],
  }),
  story({
    id: 'S1-VB-04',
    epic: 'E3',
    github: 16,
    title: 'Admin console: institutions, users, role assignment',
    owner: 'Vishal Bharath R',
    handle: '@vishalbharath',
    points: 3,
    priority: 'P1',
    area: 'area:frontend',
    type: 'frontend',
    userValue: 'Admins manage institutions and user roles in web-admin.',
    contractImpact: 'Admin user/institution APIs',
    blockedBy: ['S1-VV-02'],
    blocks: [],
    acceptanceCriteria: [
      'List institutions',
      'List users',
      'Assign role UI',
      'RBAC-protected routes',
    ],
    failureModes: ['Non-admin cannot access'],
    demoScript: 'Admin login → assign PLACEMENT_STAFF role.',
    subtasks: ['web-admin pages', 'API client hooks', 'Forms + validation'],
  }),
  story({
    id: 'S1-RM-01',
    epic: 'E4',
    github: 17,
    title:
      'ai-gateway: Redis token bucket 200 RPM / 10k TPM + 3 priority queues (P1 reserves 40 %)',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 8,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'AI calls are fairly queued and cost-bounded under load.',
    contractImpact: 'AI gateway health DTO',
    blockedBy: [],
    blocks: ['S1-RM-02', 'S1-RM-04'],
    acceptanceCriteria: [
      '200 RPM / 10k TPM token bucket in Redis',
      '3 priority queues; P1 reserves 40%',
      '/ai/health reports queue depth',
    ],
    failureModes: ['Queue full returns 503 with retry hint'],
    demoScript: 'Burst AI calls → throttling observable in metrics.',
    subtasks: [
      'Token bucket service',
      'Priority queue workers',
      'Health endpoint',
      'Load test script',
    ],
  }),
  story({
    id: 'S1-RM-02',
    epic: 'E4',
    github: 18,
    title:
      'Circuit breaker → Gemini 2.5 on 429/5xx/timeout, with integration test that forces failover',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 5,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'Assessment grading continues when Anthropic is down.',
    contractImpact: 'Provider field in audit DTO',
    blockedBy: ['S1-RM-01'],
    blocks: [],
    acceptanceCriteria: [
      'Circuit opens on 429/5xx/timeout',
      'Gemini 2.5 handles request when open',
      'Integration test forces failover',
    ],
    failureModes: ['Both providers down returns structured error'],
    demoScript: 'Disable Anthropic key → call still returns via Gemini.',
    subtasks: ['Circuit breaker impl', 'Gemini client path', 'Forced failover integration test'],
  }),
  story({
    id: 'S1-RM-03',
    epic: 'E4',
    github: 19,
    title: 'pgvector store + embedding service for competency blueprints, BARS anchors, JD vectors',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 5,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'Semantic search over competencies and anchors for grading/matching.',
    contractImpact: 'Embedding metadata types',
    blockedBy: [],
    blocks: ['S1-VG-04'],
    acceptanceCriteria: [
      'pgvector table(s) with indexes',
      'Embedding service abstraction',
      'Upsert + similarity query APIs',
    ],
    failureModes: ['Dimension mismatch rejected', 'Empty index handled'],
    demoScript: 'Embed sample text → query returns nearest neighbor.',
    subtasks: [
      'Schema migration (VV steward review)',
      'Embedding provider adapter',
      'Vector CRUD service',
      'Tests',
    ],
  }),
  story({
    id: 'S1-RM-04',
    epic: 'E4',
    github: 20,
    title:
      'claude_evaluation_audits write on every call: tokens, model, latency, cost, provider used',
    owner: 'Ramansh',
    handle: '@Ram9012',
    points: 3,
    priority: 'P0',
    area: 'area:ai',
    type: 'ai',
    userValue: 'Every AI call is auditable for cost and compliance.',
    contractImpact: 'Audit row shape',
    blockedBy: ['S1-RM-01'],
    blocks: [],
    acceptanceCriteria: [
      'Row written on every gateway call',
      'Fields: tokens, model, latency, cost, provider',
      'No PII in audit payload',
    ],
    failureModes: ['Audit write failure logged; call policy documented'],
    demoScript: 'AI call → row in claude_evaluation_audits.',
    subtasks: ['Prisma model', 'Interceptor/hook on gateway', 'Unit test'],
  }),
  story({
    id: 'S1-VG-01',
    epic: 'E5',
    github: 21,
    title: 'Item banks for MBA Finance + Business Analytics: 40 items each, weighted',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 8,
    priority: 'P0',
    area: 'area:data',
    type: 'backend',
    userValue: 'Two lead tracks have real weighted item banks for L1 delivery.',
    contractImpact: 'Item schema in content-pipeline',
    blockedBy: [],
    blocks: ['S1-VB-02'],
    acceptanceCriteria: [
      '40 items per track in Git-reviewed JSON',
      'Domain weights A–E applied',
      'content-pipeline validate passes in CI',
      'Seeded to DB/cache for warm path',
    ],
    failureModes: ['Invalid item rejected by validate'],
    demoScript: 'validate CLI green; next-item returns Finance item.',
    subtasks: [
      'Author 40 Finance items',
      'Author 40 BA items',
      'Weight metadata',
      'Seed + cache warm',
    ],
  }),
  story({
    id: 'S1-VG-02',
    epic: 'E5',
    github: 22,
    title:
      'calibration: panel CRUD, Angoff estimate capture, cut-score derivation (μ ± σ) and publish',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 8,
    priority: 'P0',
    area: 'area:data',
    type: 'backend',
    userValue: 'Published cut scores make tiers defensible for pilot tracks.',
    contractImpact: 'Calibration DTOs',
    blockedBy: [],
    blocks: ['S1-VG-03'],
    acceptanceCriteria: [
      'Panel CRUD APIs',
      'Angoff estimate capture',
      'Cut score μ ± σ derivation',
      'Publish workflow for Finance + BA',
    ],
    failureModes: ['Publish without panel quorum blocked'],
    demoScript: 'Publish cut scores → visible in catalog API.',
    subtasks: [
      'calibration module CRUD',
      'Angoff capture endpoints',
      'scoring-engine integration',
      'Publish flag',
    ],
  }),
  story({
    id: 'S1-VG-03',
    epic: 'E5',
    github: 23,
    title: 'catalog parallel-form selector + exposure tracking + item retirement flag',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 5,
    priority: 'P0',
    area: 'area:data',
    type: 'backend',
    userValue: 'Items rotate fairly and overexposed items retire.',
    contractImpact: 'Catalog selection DTO',
    blockedBy: ['S1-VG-02'],
    blocks: [],
    acceptanceCriteria: [
      'Parallel-form selection algorithm',
      'Exposure counter per item',
      'Retirement flag honored in next-item',
    ],
    failureModes: ['All items retired returns clear error'],
    demoScript: 'Multiple starts get different forms; exposure increments.',
    subtasks: ['Selector service', 'Exposure tracking', 'Retirement filter', 'Tests'],
  }),
  story({
    id: 'S1-VG-04',
    epic: 'E5',
    github: 24,
    title: 'content-pipeline embed — pushes BARS anchors and competency text into pgvector',
    owner: 'Vedika G',
    handle: '@11vedikaa',
    points: 3,
    priority: 'P1',
    area: 'area:data',
    type: 'backend',
    userValue: 'Content embeddings power semantic features in AI gateway.',
    contractImpact: 'none',
    blockedBy: ['S1-RM-03'],
    blocks: [],
    acceptanceCriteria: [
      'CLI embed command',
      'Pushes anchors + competency text to pgvector',
      'Idempotent re-embed',
    ],
    failureModes: ['Partial embed reported; retry safe'],
    demoScript: 'pnpm content embed → vectors queryable.',
    subtasks: ['embed subcommand', 'Batch upsert to vector store', 'CLI test'],
  }),
];
