/**
 * INF-06 — Beginner question bank seed: Universal Core + Software Development.
 *
 * Sprint 1 scope: 8 highest-priority skills x 10 Beginner questions = 80 questions.
 * All questions are PENDING_HUMAN_REVIEW until approved by a domain reviewer.
 * skillCode resolves against SKILL_DEFINITIONS in INF-05.
 *
 * Generated from: SMART_Framework_Universal_and_SoftwareDev_Bank.xlsx
 * Owner: Vedika G (INF-06)
 */

import type { Question } from './question.js';

export const QUESTION_BANK_UNI_SDE_BEGINNER: readonly Question[] = [
  {
    id: 'UNI-01-001',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `Its value cannot be changed after creation; any modification returns a new object`,
      B: `It is automatically stored in CPU registers`,
      C: `It can only store integer primitive values`,
      D: `Its value can be modified in-place at any time`,
    },
    answer: `A`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-002',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The function returns null immediately`,
      B: `The compiler automatically converts it to a while loop`,
      C: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      D: `The execution shifts to kernel mode`,
    },
    answer: `C`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-003',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      B: `B is evaluated before A`,
      C: `An exception is raised if B is null`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `A`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-004',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Restricted to the enclosing block or function execution context`,
      B: `Persists across process restarts`,
      C: `Shared among all threads by default`,
      D: `Accessible globally across all modules`,
    },
    answer: `A`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-005',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `The function receives the direct memory pointer`,
      B: `An error occurs if the value is zero`,
      C: `The original variable is mutated by the function`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-006',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Converting data into machine code instructions`,
      B: `Allocating dynamic heap memory`,
      C: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      D: `Automatic conversion performed by the compiler`,
    },
    answer: `C`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-007',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `The termination condition of a loop`,
      B: `A variable that changes on every loop iteration`,
      C: `A logical condition that remains True before and after each iteration of a loop`,
      D: `The index counter of a for loop`,
    },
    answer: `C`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-008',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Length returns bytes instead of element count`,
      B: `Arrays must be accessed backwards`,
      C: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
      D: `Arrays can only store up to index 10`,
    },
    answer: `C`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-009',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floating-point numbers cannot store negative numbers`,
      B: `Floating-point operations run on the GPU only`,
      C: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
      D: `Floats automatically round to integers`,
    },
    answer: `C`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-01-010',
    stream: 'UNIVERSAL',
    skillCode: 'PROGRAMMING_FUNDAMENTALS_LOGIC',
    skillName: 'Programming fundamentals & logic',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Programming fundamentals & logic - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      B: `Overriding occurs only in C`,
      C: `Overloading changes variable scope`,
      D: `Overloading requires multithreading`,
    },
    answer: `A`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-001',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `It is automatically stored in CPU registers`,
      B: `Its value cannot be changed after creation; any modification returns a new object`,
      C: `Its value can be modified in-place at any time`,
      D: `It can only store integer primitive values`,
    },
    answer: `B`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-002',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The compiler automatically converts it to a while loop`,
      B: `The function returns null immediately`,
      C: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      D: `The execution shifts to kernel mode`,
    },
    answer: `C`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-003',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `B is evaluated before A`,
      B: `An exception is raised if B is null`,
      C: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `C`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-004',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Shared among all threads by default`,
      B: `Persists across process restarts`,
      C: `Restricted to the enclosing block or function execution context`,
      D: `Accessible globally across all modules`,
    },
    answer: `C`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-005',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `A copy of the value is passed; changes inside the function do not affect the original variable`,
      B: `The original variable is mutated by the function`,
      C: `The function receives the direct memory pointer`,
      D: `An error occurs if the value is zero`,
    },
    answer: `A`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-006',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Converting data into machine code instructions`,
      B: `Allocating dynamic heap memory`,
      C: `Automatic conversion performed by the compiler`,
      D: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
    },
    answer: `D`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-007',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `The termination condition of a loop`,
      B: `A logical condition that remains True before and after each iteration of a loop`,
      C: `A variable that changes on every loop iteration`,
      D: `The index counter of a for loop`,
    },
    answer: `B`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-008',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Length returns bytes instead of element count`,
      B: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
      C: `Arrays must be accessed backwards`,
      D: `Arrays can only store up to index 10`,
    },
    answer: `B`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-009',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
      B: `Floating-point operations run on the GPU only`,
      C: `Floats automatically round to integers`,
      D: `Floating-point numbers cannot store negative numbers`,
    },
    answer: `A`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-02-010',
    stream: 'UNIVERSAL',
    skillCode: 'DATA_STRUCTURES_ALGORITHMS',
    skillName: 'Data structures & algorithms',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Data structures & algorithms - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      B: `Overloading requires multithreading`,
      C: `Overloading changes variable scope`,
      D: `Overriding occurs only in C`,
    },
    answer: `A`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-001',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `Its value can be modified in-place at any time`,
      B: `It can only store integer primitive values`,
      C: `It is automatically stored in CPU registers`,
      D: `Its value cannot be changed after creation; any modification returns a new object`,
    },
    answer: `D`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-002',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The execution shifts to kernel mode`,
      B: `The compiler automatically converts it to a while loop`,
      C: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      D: `The function returns null immediately`,
    },
    answer: `C`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-003',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `Both A and B are always evaluated simultaneously`,
      B: `B is evaluated before A`,
      C: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      D: `An exception is raised if B is null`,
    },
    answer: `C`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-004',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Shared among all threads by default`,
      B: `Restricted to the enclosing block or function execution context`,
      C: `Persists across process restarts`,
      D: `Accessible globally across all modules`,
    },
    answer: `B`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-005',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `The original variable is mutated by the function`,
      B: `An error occurs if the value is zero`,
      C: `The function receives the direct memory pointer`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-006',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Automatic conversion performed by the compiler`,
      B: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      C: `Allocating dynamic heap memory`,
      D: `Converting data into machine code instructions`,
    },
    answer: `B`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-007',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `A variable that changes on every loop iteration`,
      B: `The index counter of a for loop`,
      C: `A logical condition that remains True before and after each iteration of a loop`,
      D: `The termination condition of a loop`,
    },
    answer: `C`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-008',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Arrays can only store up to index 10`,
      B: `Arrays must be accessed backwards`,
      C: `Length returns bytes instead of element count`,
      D: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
    },
    answer: `D`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-009',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floats automatically round to integers`,
      B: `Floating-point operations run on the GPU only`,
      C: `Floating-point numbers cannot store negative numbers`,
      D: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
    },
    answer: `D`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-03-010',
    stream: 'UNIVERSAL',
    skillCode: 'OBJECT_ORIENTED_PROGRAMMING',
    skillName: 'Object-oriented programming',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Object-oriented programming - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading requires multithreading`,
      B: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      C: `Overriding occurs only in C`,
      D: `Overloading changes variable scope`,
    },
    answer: `B`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-001',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `It is automatically stored in CPU registers`,
      B: `Its value cannot be changed after creation; any modification returns a new object`,
      C: `Its value can be modified in-place at any time`,
      D: `It can only store integer primitive values`,
    },
    answer: `B`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-002',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      B: `The execution shifts to kernel mode`,
      C: `The compiler automatically converts it to a while loop`,
      D: `The function returns null immediately`,
    },
    answer: `A`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-003',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `An exception is raised if B is null`,
      B: `Both A and B are always evaluated simultaneously`,
      C: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      D: `B is evaluated before A`,
    },
    answer: `C`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-004',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Accessible globally across all modules`,
      B: `Persists across process restarts`,
      C: `Shared among all threads by default`,
      D: `Restricted to the enclosing block or function execution context`,
    },
    answer: `D`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-005',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `An error occurs if the value is zero`,
      B: `The original variable is mutated by the function`,
      C: `The function receives the direct memory pointer`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-006',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      B: `Allocating dynamic heap memory`,
      C: `Automatic conversion performed by the compiler`,
      D: `Converting data into machine code instructions`,
    },
    answer: `A`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-007',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `The termination condition of a loop`,
      B: `A variable that changes on every loop iteration`,
      C: `A logical condition that remains True before and after each iteration of a loop`,
      D: `The index counter of a for loop`,
    },
    answer: `C`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-008',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Arrays must be accessed backwards`,
      B: `Arrays can only store up to index 10`,
      C: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
      D: `Length returns bytes instead of element count`,
    },
    answer: `C`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-009',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floating-point numbers cannot store negative numbers`,
      B: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
      C: `Floating-point operations run on the GPU only`,
      D: `Floats automatically round to integers`,
    },
    answer: `B`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-04-010',
    stream: 'UNIVERSAL',
    skillCode: 'DATABASE_FUNDAMENTALS',
    skillName: 'Database fundamentals (SQL/DBMS)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Database fundamentals (SQL/DBMS) - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overriding occurs only in C`,
      B: `Overloading changes variable scope`,
      C: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      D: `Overloading requires multithreading`,
    },
    answer: `C`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-001',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `It is automatically stored in CPU registers`,
      B: `Its value can be modified in-place at any time`,
      C: `Its value cannot be changed after creation; any modification returns a new object`,
      D: `It can only store integer primitive values`,
    },
    answer: `C`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-002',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      B: `The execution shifts to kernel mode`,
      C: `The function returns null immediately`,
      D: `The compiler automatically converts it to a while loop`,
    },
    answer: `A`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-003',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `An exception is raised if B is null`,
      B: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      C: `B is evaluated before A`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `B`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-004',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Persists across process restarts`,
      B: `Shared among all threads by default`,
      C: `Accessible globally across all modules`,
      D: `Restricted to the enclosing block or function execution context`,
    },
    answer: `D`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-005',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `The function receives the direct memory pointer`,
      B: `The original variable is mutated by the function`,
      C: `A copy of the value is passed; changes inside the function do not affect the original variable`,
      D: `An error occurs if the value is zero`,
    },
    answer: `C`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-006',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      B: `Converting data into machine code instructions`,
      C: `Allocating dynamic heap memory`,
      D: `Automatic conversion performed by the compiler`,
    },
    answer: `A`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-007',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `The termination condition of a loop`,
      B: `The index counter of a for loop`,
      C: `A logical condition that remains True before and after each iteration of a loop`,
      D: `A variable that changes on every loop iteration`,
    },
    answer: `C`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-008',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Length returns bytes instead of element count`,
      B: `Arrays can only store up to index 10`,
      C: `Arrays must be accessed backwards`,
      D: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
    },
    answer: `D`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-009',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floating-point operations run on the GPU only`,
      B: `Floats automatically round to integers`,
      C: `Floating-point numbers cannot store negative numbers`,
      D: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
    },
    answer: `D`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-05-010',
    stream: 'UNIVERSAL',
    skillCode: 'OPERATING_SYSTEMS_CONCEPTS',
    skillName: 'Operating systems concepts',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Operating systems concepts - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      B: `Overloading requires multithreading`,
      C: `Overriding occurs only in C`,
      D: `Overloading changes variable scope`,
    },
    answer: `A`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-001',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `Its value can be modified in-place at any time`,
      B: `It can only store integer primitive values`,
      C: `Its value cannot be changed after creation; any modification returns a new object`,
      D: `It is automatically stored in CPU registers`,
    },
    answer: `C`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-002',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The execution shifts to kernel mode`,
      B: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
      C: `The function returns null immediately`,
      D: `The compiler automatically converts it to a while loop`,
    },
    answer: `B`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-003',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `B is evaluated before A`,
      B: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      C: `An exception is raised if B is null`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `B`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-004',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Shared among all threads by default`,
      B: `Accessible globally across all modules`,
      C: `Persists across process restarts`,
      D: `Restricted to the enclosing block or function execution context`,
    },
    answer: `D`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-005',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `An error occurs if the value is zero`,
      B: `The function receives the direct memory pointer`,
      C: `The original variable is mutated by the function`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-006',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Converting data into machine code instructions`,
      B: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      C: `Allocating dynamic heap memory`,
      D: `Automatic conversion performed by the compiler`,
    },
    answer: `B`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-007',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `The termination condition of a loop`,
      B: `The index counter of a for loop`,
      C: `A logical condition that remains True before and after each iteration of a loop`,
      D: `A variable that changes on every loop iteration`,
    },
    answer: `C`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-008',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Length returns bytes instead of element count`,
      B: `Arrays can only store up to index 10`,
      C: `Arrays must be accessed backwards`,
      D: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
    },
    answer: `D`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-009',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floats automatically round to integers`,
      B: `Floating-point operations run on the GPU only`,
      C: `Floating-point numbers cannot store negative numbers`,
      D: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
    },
    answer: `D`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-06-010',
    stream: 'UNIVERSAL',
    skillCode: 'COMPUTER_NETWORKS_BASICS',
    skillName: 'Computer networks basics',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Computer networks basics - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading requires multithreading`,
      B: `Overriding occurs only in C`,
      C: `Overloading changes variable scope`,
      D: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
    },
    answer: `D`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-001',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `It is automatically stored in CPU registers`,
      B: `It can only store integer primitive values`,
      C: `Its value cannot be changed after creation; any modification returns a new object`,
      D: `Its value can be modified in-place at any time`,
    },
    answer: `C`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-002',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The function returns null immediately`,
      B: `The execution shifts to kernel mode`,
      C: `The compiler automatically converts it to a while loop`,
      D: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
    },
    answer: `D`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-003',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `B is evaluated before A`,
      B: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      C: `An exception is raised if B is null`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `B`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-004',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Shared among all threads by default`,
      B: `Accessible globally across all modules`,
      C: `Restricted to the enclosing block or function execution context`,
      D: `Persists across process restarts`,
    },
    answer: `C`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-005',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `The original variable is mutated by the function`,
      B: `The function receives the direct memory pointer`,
      C: `An error occurs if the value is zero`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-006',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Allocating dynamic heap memory`,
      B: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      C: `Converting data into machine code instructions`,
      D: `Automatic conversion performed by the compiler`,
    },
    answer: `B`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-007',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `A logical condition that remains True before and after each iteration of a loop`,
      B: `A variable that changes on every loop iteration`,
      C: `The index counter of a for loop`,
      D: `The termination condition of a loop`,
    },
    answer: `A`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-008',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Length returns bytes instead of element count`,
      B: `Arrays must be accessed backwards`,
      C: `Arrays can only store up to index 10`,
      D: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
    },
    answer: `D`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-009',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floating-point operations run on the GPU only`,
      B: `Floating-point numbers cannot store negative numbers`,
      C: `Floats automatically round to integers`,
      D: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
    },
    answer: `D`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'UNI-07-010',
    stream: 'UNIVERSAL',
    skillCode: 'GIT_VERSION_CONTROL',
    skillName: 'Git & version control',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Git & version control - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading changes variable scope`,
      B: `Overloading requires multithreading`,
      C: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
      D: `Overriding occurs only in C`,
    },
    answer: `C`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-001',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What is the primary characteristic of an immutable variable or object in programming languages?`,
    options: {
      A: `Its value can be modified in-place at any time`,
      B: `It is automatically stored in CPU registers`,
      C: `Its value cannot be changed after creation; any modification returns a new object`,
      D: `It can only store integer primitive values`,
    },
    answer: `C`,
    rubric: `Immutable objects (e.g. tuples, strings in Python) cannot be altered after instantiation, guaranteeing thread safety and hashability.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-002',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What occurs if a recursive function lacks a properly defined base condition?`,
    options: {
      A: `The execution shifts to kernel mode`,
      B: `The function returns null immediately`,
      C: `The compiler automatically converts it to a while loop`,
      D: `The call stack overflows resulting in a StackOverflow / Maximum Recursion Depth error`,
    },
    answer: `D`,
    rubric: `Without a base case, recursive calls continue appending stack frames until stack memory limit is exceeded.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-003',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] How does logical short-circuit evaluation behave in boolean expressions containing \`A AND B\`?`,
    options: {
      A: `B is evaluated before A`,
      B: `If A evaluates to False, B is not evaluated because the entire expression is guaranteed False`,
      C: `An exception is raised if B is null`,
      D: `Both A and B are always evaluated simultaneously`,
    },
    answer: `B`,
    rubric: `In AND operations, if the first operand is False, evaluating the second operand is redundant and skipped.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-004',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What is the scope of a local variable declared inside a block or function?`,
    options: {
      A: `Shared among all threads by default`,
      B: `Accessible globally across all modules`,
      C: `Restricted to the enclosing block or function execution context`,
      D: `Persists across process restarts`,
    },
    answer: `C`,
    rubric: `Local variables exist only within their enclosing stack frame and are destroyed when the frame pops.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-005',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] When passing a primitive integer to a function in pass-by-value semantics, what happens to the original variable?`,
    options: {
      A: `An error occurs if the value is zero`,
      B: `The original variable is mutated by the function`,
      C: `The function receives the direct memory pointer`,
      D: `A copy of the value is passed; changes inside the function do not affect the original variable`,
    },
    answer: `D`,
    rubric: `Pass-by-value creates a local copy, decoupling changes inside the function scope from the caller's variable.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-006',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What is explicit type casting in typed programming languages?`,
    options: {
      A: `Manual conversion performed by the developer using explicit syntax (e.g., int(x) or (int)x)`,
      B: `Allocating dynamic heap memory`,
      C: `Converting data into machine code instructions`,
      D: `Automatic conversion performed by the compiler`,
    },
    answer: `A`,
    rubric: `Explicit type casting (type conversion) forces a value from one data type to another intentionally.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-007',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What is a loop invariant in algorithm verification?`,
    options: {
      A: `A variable that changes on every loop iteration`,
      B: `A logical condition that remains True before and after each iteration of a loop`,
      C: `The termination condition of a loop`,
      D: `The index counter of a for loop`,
    },
    answer: `B`,
    rubric: `A loop invariant is a property that holds true initially, after every iteration, and upon loop termination.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-008',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] Why does accessing an array at index equal to its length (e.g. arr[len]) cause an error in 0-indexed languages?`,
    options: {
      A: `Arrays can only store up to index 10`,
      B: `Length returns bytes instead of element count`,
      C: `Arrays must be accessed backwards`,
      D: `0-indexed arrays of length N have valid indices from 0 to N-1; index N is out of bounds`,
    },
    answer: `D`,
    rubric: `In 0-indexed structures, the final valid element resides at index N-1.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-009',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] Why can binary floating-point representation (IEEE 754) lead to exact comparisons failing (e.g. 0.1 + 0.2 != 0.3)?`,
    options: {
      A: `Floating-point operations run on the GPU only`,
      B: `Floating-point numbers cannot store negative numbers`,
      C: `Floats automatically round to integers`,
      D: `Certain decimal fractions cannot be represented exactly in base-2 binary floating point`,
    },
    answer: `D`,
    rubric: `Fractions like 0.1 have repeating infinite binary representations, leading to minor precision rounding errors.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
  {
    id: 'SDE-08-010',
    stream: 'SOFTWARE_DEVELOPMENT',
    skillCode: 'LANGUAGE_PROFICIENCY',
    skillName: 'Language proficiency (Java/Python/JS/C++)',
    level: 'BEGINNER',
    format: 'MCQ',
    prompt: `[Language proficiency (Java/Python/JS/C++) - Beginner] What distinguishes function overloading from function overriding?`,
    options: {
      A: `Overloading changes variable scope`,
      B: `Overriding occurs only in C`,
      C: `Overloading requires multithreading`,
      D: `Overloading defines multiple functions in the same scope with identical names but different parameter signatures`,
    },
    answer: `D`,
    rubric: `Overloading provides multiple implementations based on parameter types/counts within the same class/scope.`,
    reviewStatus: 'PENDING_HUMAN_REVIEW',
  },
] as const;
